/**
 * Bare Bones EDI: A bare-bones C library for EDI files
 * Copyright (C) 2025 Ian Wang
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef BARE_BONES_EDI_SEGMENT_H
#define BARE_BONES_EDI_SEGMENT_H

#define NIL 0
#define EDI_HASH(X, Y, Z) \
    ( (X) << (0 << 3)     \
    | (Y) << (1 << 3)     \
    | (Z) << (2 << 3) )

typedef enum {

    X12_SEGMENT_AAA = EDI_HASH('A', 'A', 'A'),  // Request Validation
    X12_SEGMENT_ACD = EDI_HASH('A', 'C', 'D'),  // Account Description
    X12_SEGMENT_ACK = EDI_HASH('A', 'C', 'K'),  // Line Item Acknowledgment
    X12_SEGMENT_ACS = EDI_HASH('A', 'C', 'S'),  // Ancillary Charges
    X12_SEGMENT_ACT = EDI_HASH('A', 'C', 'T'),  // Account Identification
    X12_SEGMENT_AD1 = EDI_HASH('A', 'D', '1'),  // Adjustment Amount
    X12_SEGMENT_ADI = EDI_HASH('A', 'D', 'I'),  // Animal Disposition
    X12_SEGMENT_ADJ = EDI_HASH('A', 'D', 'J'),  // Adjustments to Balances or Services
    X12_SEGMENT_ADT = EDI_HASH('A', 'D', 'T'),  // Animal Parturition Status
    X12_SEGMENT_ADV = EDI_HASH('A', 'D', 'V'),  // Advertising Demographic Information
    X12_SEGMENT_ADX = EDI_HASH('A', 'D', 'X'),  // Adjustment
    X12_SEGMENT_AEI = EDI_HASH('A', 'E', 'I'),  // Equipment Information Summary
    X12_SEGMENT_AES = EDI_HASH('A', 'E', 'S'),  // Automatic Equipment Identification Site Information
    X12_SEGMENT_AIN = EDI_HASH('A', 'I', 'N'),  // Income
    X12_SEGMENT_AK1 = EDI_HASH('A', 'K', '1'),  // Functional Group Response Header
    X12_SEGMENT_AK2 = EDI_HASH('A', 'K', '2'),  // Transaction Set Response Header
    X12_SEGMENT_AK3 = EDI_HASH('A', 'K', '3'),  // Data Segment Note
    X12_SEGMENT_AK4 = EDI_HASH('A', 'K', '4'),  // Data Element Note
    X12_SEGMENT_AK5 = EDI_HASH('A', 'K', '5'),  // Transaction Set Response Trailer
    X12_SEGMENT_AK9 = EDI_HASH('A', 'K', '9'),  // Functional Group Response Trailer
    X12_SEGMENT_ALG = EDI_HASH('A', 'L', 'G'),  // Allergen
    X12_SEGMENT_AM1 = EDI_HASH('A', 'M', '1'),  // Informational Values
    X12_SEGMENT_AMT = EDI_HASH('A', 'M', 'T'),  // Monetary Amount Information
    X12_SEGMENT_ANI = EDI_HASH('A', 'N', 'I'),  // Animal Identification
    X12_SEGMENT_AOC = EDI_HASH('A', 'O', 'C'),  // Animal Offspring Counts
    X12_SEGMENT_AOI = EDI_HASH('A', 'O', 'I'),  // Animal Offspring/Fetus Identification
    X12_SEGMENT_AOL = EDI_HASH('A', 'O', 'L'),  // Animal Observation Location
    X12_SEGMENT_AOR = EDI_HASH('A', 'O', 'R'),  // Animal Observation Result
    X12_SEGMENT_AP1 = EDI_HASH('A', 'P', '1'),  // Alternate Parts
    X12_SEGMENT_APE = EDI_HASH('A', 'P', 'E'),  // Assurance Protocol Error
    X12_SEGMENT_API = EDI_HASH('A', 'P', 'I'),  // Activity or Process Information
    X12_SEGMENT_APR = EDI_HASH('A', 'P', 'R'),  // Association of American Railroads Pool Code Restrictions
    X12_SEGMENT_ARC = EDI_HASH('A', 'R', 'C'),  // Animal Results Counts
    X12_SEGMENT_ARS = EDI_HASH('A', 'R', 'S'),  // Applicant Residence Specifics
    X12_SEGMENT_ASI = EDI_HASH('A', 'S', 'I'),  // Action or Status Indicator
    X12_SEGMENT_ASL = EDI_HASH('A', 'S', 'L'),  // Asset Liability
    X12_SEGMENT_ASM = EDI_HASH('A', 'S', 'M'),  // Amount and Settlement Method
    X12_SEGMENT_ASO = EDI_HASH('A', 'S', 'O'),  // Asset Ownership
    X12_SEGMENT_AST = EDI_HASH('A', 'S', 'T'),  // Animal Reproductive Status
    X12_SEGMENT_AT1 = EDI_HASH('A', 'T', '1'),  // Bill of Lading Line Item Number
    X12_SEGMENT_AT2 = EDI_HASH('A', 'T', '2'),  // Bill of Lading Line Item Detail
    X12_SEGMENT_AT3 = EDI_HASH('A', 'T', '3'),  // Bill of Lading Rates and Charges
    X12_SEGMENT_AT4 = EDI_HASH('A', 'T', '4'),  // Bill of Lading Description
    X12_SEGMENT_AT5 = EDI_HASH('A', 'T', '5'),  // Bill of Lading Handling Requirements
    X12_SEGMENT_AT6 = EDI_HASH('A', 'T', '6'),  // International Manifest Information
    X12_SEGMENT_AT7 = EDI_HASH('A', 'T', '7'),  // Shipment Status Details
    X12_SEGMENT_AT8 = EDI_HASH('A', 'T', '8'),  // Shipment Weight, Packaging and Quantity Data
    X12_SEGMENT_AT9 = EDI_HASH('A', 'T', '9'),  // Trailer or Container Dimension and Weight
    X12_SEGMENT_ATA = EDI_HASH('A', 'T', 'A'),  // Beginning Segment for Motor Carrier Delivery Trailer Manifest
    X12_SEGMENT_ATH = EDI_HASH('A', 'T', 'H'),  // Resource Authorization
    X12_SEGMENT_ATN = EDI_HASH('A', 'T', 'N'),  // Attendance
    X12_SEGMENT_ATR = EDI_HASH('A', 'T', 'R'),  // Animal Test Result
    X12_SEGMENT_ATV = EDI_HASH('A', 'T', 'V'),  // Student Activities and Awards
    X12_SEGMENT_AVA = EDI_HASH('A', 'V', 'A'),  // Funds Availability
    X12_SEGMENT_AWD = EDI_HASH('A', 'W', 'D'),  // Amount with Description
    X12_SEGMENT_AXL = EDI_HASH('A', 'X', 'L'),  // Vehicle Axle Measurements
    X12_SEGMENT_B1  = EDI_HASH('B', '1', NIL),  // Beginning Segment for Booking or Pickup/Delivery
    X12_SEGMENT_B10 = EDI_HASH('B', '1', '0'),  // Beginning Segment for Transportation Carrier Shipment Status Message
    X12_SEGMENT_B11 = EDI_HASH('B', '1', '1'),  // Beginning Segment for Shipment Status Inquiry
    X12_SEGMENT_B12 = EDI_HASH('B', '1', '2'),  // Beginning Segment for Consolidation of Goods In Container
    X12_SEGMENT_B13 = EDI_HASH('B', '1', '3'),  // Beginning Segment for Appointment Schedule
    X12_SEGMENT_B2  = EDI_HASH('B', '2', NIL),  // Beginning Segment for Shipment Information Transaction
    X12_SEGMENT_B2A = EDI_HASH('B', '2', 'A'),  // Set Purpose
    X12_SEGMENT_B3  = EDI_HASH('B', '3', NIL),  // Beginning Segment for Carrier's Invoice
    X12_SEGMENT_B3A = EDI_HASH('B', '3', 'A'),  // Invoice Type
    X12_SEGMENT_B3B = EDI_HASH('B', '3', 'B'),  // Beginning Segment for Rail Carrier's Invoice
    X12_SEGMENT_B4  = EDI_HASH('B', '4', NIL),  // Beginning Segment for Inquiry or Reply
    X12_SEGMENT_B9  = EDI_HASH('B', '9', NIL),  // Beginning Segment for Logistics Services
    X12_SEGMENT_B9A = EDI_HASH('B', '9', 'A'),  // Service Request
    X12_SEGMENT_BA1 = EDI_HASH('B', 'A', '1'),  // Export Shipment Identifying Information
    X12_SEGMENT_BA2 = EDI_HASH('B', 'A', '2'),  // Beginning Segment for Cargo Terminal Information
    X12_SEGMENT_BAA = EDI_HASH('B', 'A', 'A'),  // Beginning Segment for Product Transfer Account Adjustment
    X12_SEGMENT_BAK = EDI_HASH('B', 'A', 'K'),  // Beginning Segment for Purchase Order Acknowledgment
    X12_SEGMENT_BAL = EDI_HASH('B', 'A', 'L'),  // Balance Detail
    X12_SEGMENT_BAT = EDI_HASH('B', 'A', 'T'),  // Batch
    X12_SEGMENT_BAU = EDI_HASH('B', 'A', 'U'),  // Beginning Segment for the Debit Authorization
    X12_SEGMENT_BAX = EDI_HASH('B', 'A', 'X'),  // Beginning Segment for Advance Consist and Transportation Automatic Equipment ID
    X12_SEGMENT_BBC = EDI_HASH('B', 'B', 'C'),  // Legal Claims
    X12_SEGMENT_BC  = EDI_HASH('B', 'C', NIL),  // Beginning Segment for Contract Completion Status
    X12_SEGMENT_BCA = EDI_HASH('B', 'C', 'A'),  // Beginning Segment for Purchase Order Change Acknowledgment
    X12_SEGMENT_BCD = EDI_HASH('B', 'C', 'D'),  // Beginning Credit/Debit Adjustment
    X12_SEGMENT_BCH = EDI_HASH('B', 'C', 'H'),  // Beginning Segment for Purchase Order Change
    X12_SEGMENT_BCI = EDI_HASH('B', 'C', 'I'),  // Basic Claim Information
    X12_SEGMENT_BCM = EDI_HASH('B', 'C', 'M'),  // Beginning Segment for Contractor Cost Data Reporting
    X12_SEGMENT_BCO = EDI_HASH('B', 'C', 'O'),  // Beginning Segment for Procurement Notices
    X12_SEGMENT_BCP = EDI_HASH('B', 'C', 'P'),  // Beginning Segment for Contract Pricing Proposal
    X12_SEGMENT_BCQ = EDI_HASH('B', 'C', 'Q'),  // Beginning Segment for Shipper's Car Order
    X12_SEGMENT_BCS = EDI_HASH('B', 'C', 'S'),  // Beginning Segment for Project Cost Reporting
    X12_SEGMENT_BCT = EDI_HASH('B', 'C', 'T'),  // Beginning Segment for Price/Sales Catalog
    X12_SEGMENT_BCU = EDI_HASH('B', 'C', 'U'),  // Legal Claim Updates
    X12_SEGMENT_BDD = EDI_HASH('B', 'D', 'D'),  // Beginning Segment for Shipment Delivery Discrepancy Information
    X12_SEGMENT_BDS = EDI_HASH('B', 'D', 'S'),  // Binary Data Structure
    X12_SEGMENT_BEG = EDI_HASH('B', 'E', 'G'),  // Beginning Segment for Purchase Order
    X12_SEGMENT_BEN = EDI_HASH('B', 'E', 'N'),  // Beneficiary or Owner Information
    X12_SEGMENT_BEP = EDI_HASH('B', 'E', 'P'),  // Borrower Education Program
    X12_SEGMENT_BER = EDI_HASH('B', 'E', 'R'),  // Beer Information
    X12_SEGMENT_BFR = EDI_HASH('B', 'F', 'R'),  // Beginning Segment for Planning Schedule
    X12_SEGMENT_BFS = EDI_HASH('B', 'F', 'S'),  // Borrower Financial Summary
    X12_SEGMENT_BGF = EDI_HASH('B', 'G', 'F'),  // Beginning Segment for File Transfer Information
    X12_SEGMENT_BGN = EDI_HASH('B', 'G', 'N'),  // Beginning Segment
    X12_SEGMENT_BGP = EDI_HASH('B', 'G', 'P'),  // Beginning Segment for Problem Log Inquiry or Advice
    X12_SEGMENT_BHT = EDI_HASH('B', 'H', 'T'),  // Beginning of Hierarchical Transaction
    X12_SEGMENT_BIA = EDI_HASH('B', 'I', 'A'),  // Beginning Segment for Inventory Inquiry/Advice
    X12_SEGMENT_BIG = EDI_HASH('B', 'I', 'G'),  // Beginning Segment for Invoice
    X12_SEGMENT_BIN = EDI_HASH('B', 'I', 'N'),  // Binary Data Segment
    X12_SEGMENT_BIX = EDI_HASH('B', 'I', 'X'),  // Beginning Segment for Automotive Inspection
    X12_SEGMENT_BJF = EDI_HASH('B', 'J', 'F'),  // Beginning Segment Railroad Junctions and Interchanges Update Activity
    X12_SEGMENT_BL  = EDI_HASH('B', 'L', NIL),  // Billing Information
    X12_SEGMENT_BLI = EDI_HASH('B', 'L', 'I'),  // Basic Baseline Item Data
    X12_SEGMENT_BLN = EDI_HASH('B', 'L', 'N'),  // Balance Information
    X12_SEGMENT_BLR = EDI_HASH('B', 'L', 'R'),  // Transportation Carrier Identification
    X12_SEGMENT_BLS = EDI_HASH('B', 'L', 'S'),  // Beginning Segment for Asset Schedule
    X12_SEGMENT_BMA = EDI_HASH('B', 'M', 'A'),  // Beginning Segment for Market Development Fund Allocation
    X12_SEGMENT_BMG = EDI_HASH('B', 'M', 'G'),  // Beginning Segment For Text Message
    X12_SEGMENT_BMM = EDI_HASH('B', 'M', 'M'),  // Beginning Segment for Multilevel Railcar Load Details Transaction
    X12_SEGMENT_BMP = EDI_HASH('B', 'M', 'P'),  // Beginning Segment for Market Development Fund Settlement
    X12_SEGMENT_BMS = EDI_HASH('B', 'M', 'S'),  // Beginning Segment For Material Safety Data Sheet
    X12_SEGMENT_BNR = EDI_HASH('B', 'N', 'R'),  // Beginning Segment For Nonconformance Report
    X12_SEGMENT_BNX = EDI_HASH('B', 'N', 'X'),  // Rail Shipment Information
    X12_SEGMENT_BOL = EDI_HASH('B', 'O', 'L'),  // Beginning Segment for the Motor Carrier Bill of Lading
    X12_SEGMENT_BOR = EDI_HASH('B', 'O', 'R'),  // Beginning of Report
    X12_SEGMENT_BOS = EDI_HASH('B', 'O', 'S'),  // Beginning Segment for Joint Interest Billing and Operating Expense Statement
    X12_SEGMENT_BOX = EDI_HASH('B', 'O', 'X'),  // Box Office Detail
    X12_SEGMENT_BPA = EDI_HASH('B', 'P', 'A'),  // Beginning Segment for Price Authorization Acknowledgment/Status
    X12_SEGMENT_BPP = EDI_HASH('B', 'P', 'P'),  // Beginning Segment for Project Schedule Reporting
    X12_SEGMENT_BPR = EDI_HASH('B', 'P', 'R'),  // Beginning Segment for Payment Order/Remittance Advice
    X12_SEGMENT_BPT = EDI_HASH('B', 'P', 'T'),  // Beginning Segment for Product Transfer and Resale
    X12_SEGMENT_BQR = EDI_HASH('B', 'Q', 'R'),  // Beginning Segment for Response to Request for Quotation
    X12_SEGMENT_BQT = EDI_HASH('B', 'Q', 'T'),  // Beginning Segment for Request for Quotation
    X12_SEGMENT_BR  = EDI_HASH('B', 'R', NIL),  // Beginning Segment for Material Management
    X12_SEGMENT_BRA = EDI_HASH('B', 'R', 'A'),  // Beginning Segment for Receiving Advice or Acceptance Certificate
    X12_SEGMENT_BRC = EDI_HASH('B', 'R', 'C'),  // Beginning Segment for Response to Product Transfer Account Adjustment
    X12_SEGMENT_BRR = EDI_HASH('B', 'R', 'R'),  // Beginning Segment for Railroad Mark Register Update Activity
    X12_SEGMENT_BSC = EDI_HASH('B', 'S', 'C'),  // Beginning Segment for Commission Sales Report and Periodic Compensation
    X12_SEGMENT_BSD = EDI_HASH('B', 'S', 'D'),  // Breakdown Structure Description
    X12_SEGMENT_BSF = EDI_HASH('B', 'S', 'F'),  // Business Function
    X12_SEGMENT_BSI = EDI_HASH('B', 'S', 'I'),  // Beginning Segment for Order Status Inquiry
    X12_SEGMENT_BSN = EDI_HASH('B', 'S', 'N'),  // Beginning Segment for Ship Notice
    X12_SEGMENT_BSR = EDI_HASH('B', 'S', 'R'),  // Beginning Segment for Order Status Report
    X12_SEGMENT_BSS = EDI_HASH('B', 'S', 'S'),  // Beginning Segment for Shipping Schedule/Production Sequence
    X12_SEGMENT_BSW = EDI_HASH('B', 'S', 'W'),  // Beginning Segment for Carrier's Services Settlement
    X12_SEGMENT_BT1 = EDI_HASH('B', 'T', '1'),  // Batch Totals
    X12_SEGMENT_BTA = EDI_HASH('B', 'T', 'A'),  // Beginning Tax Acknowledgment
    X12_SEGMENT_BTC = EDI_HASH('B', 'T', 'C'),  // Beginning Segment for Parameter Trace Registration
    X12_SEGMENT_BTI = EDI_HASH('B', 'T', 'I'),  // Beginning Tax Information
    X12_SEGMENT_BTP = EDI_HASH('B', 'T', 'P'),  // Beginning Segment For Trading Partner Profile
    X12_SEGMENT_BTR = EDI_HASH('B', 'T', 'R'),  // Beginning Segment for Test Results
    X12_SEGMENT_BTS = EDI_HASH('B', 'T', 'S'),  // Beginning Segment for Train Sheets
    X12_SEGMENT_BUY = EDI_HASH('B', 'U', 'Y'),  // Loan Buydown
    X12_SEGMENT_BVA = EDI_HASH('B', 'V', 'A'),  // Beginning Vehicle Advice
    X12_SEGMENT_BVB = EDI_HASH('B', 'V', 'B'),  // Beginning Segment for Vehicle Baying Order
    X12_SEGMENT_BVI = EDI_HASH('B', 'V', 'I'),  // Beverage Information
    X12_SEGMENT_BVP = EDI_HASH('B', 'V', 'P'),  // Beginning Segment for Vehicle Shipping Order
    X12_SEGMENT_BVS = EDI_HASH('B', 'V', 'S'),  // Beginning Segment for Vehicle Service
    X12_SEGMENT_BW  = EDI_HASH('B', 'W', NIL),  // Beginning Segment for Weight Message Set
    X12_SEGMENT_BX  = EDI_HASH('B', 'X', NIL),  // General Shipment Information
    X12_SEGMENT_C2  = EDI_HASH('C', '2', NIL),  // Bank ID
    X12_SEGMENT_C3  = EDI_HASH('C', '3', NIL),  // Currency Identifier
    X12_SEGMENT_C4  = EDI_HASH('C', '4', NIL),  // Alternate Amount Due
    X12_SEGMENT_C8  = EDI_HASH('C', '8', NIL),  // Certifications and Clauses
    X12_SEGMENT_C8C = EDI_HASH('C', '8', 'C'),  // Certifications Clauses Continuation
    X12_SEGMENT_CA1 = EDI_HASH('C', 'A', '1'),  // Rate Request Identifier
    X12_SEGMENT_CAD = EDI_HASH('C', 'A', 'D'),  // Carrier Details
    X12_SEGMENT_CAI = EDI_HASH('C', 'A', 'I'),  // Civil Action Income
    X12_SEGMENT_CAL = EDI_HASH('C', 'A', 'L'),  // Calendar
    X12_SEGMENT_CAS = EDI_HASH('C', 'A', 'S'),  // Claims Adjustment
    X12_SEGMENT_CAT = EDI_HASH('C', 'A', 'T'),  // Category of Patient Information Service
    X12_SEGMENT_CB1 = EDI_HASH('C', 'B', '1'),  // Contract and Cost Accounting Standards Data
    X12_SEGMENT_CBS = EDI_HASH('C', 'B', 'S'),  // Cost Breakdown Structure
    X12_SEGMENT_CCI = EDI_HASH('C', 'C', 'I'),  // Credit Counseling Information
    X12_SEGMENT_CD  = EDI_HASH('C', 'D', NIL),  // Shipment Conditions
    X12_SEGMENT_CD1 = EDI_HASH('C', 'D', '1'),  // Cargo Detail
    X12_SEGMENT_CD2 = EDI_HASH('C', 'D', '2'),  // Multi-Valued Characteristics
    X12_SEGMENT_CD3 = EDI_HASH('C', 'D', '3'),  // Carton (Package) Detail
    X12_SEGMENT_CDA = EDI_HASH('C', 'D', 'A'),  // Consumer Credit Account
    X12_SEGMENT_CDD = EDI_HASH('C', 'D', 'D'),  // Credit/Debit Adjustment Detail
    X12_SEGMENT_CDI = EDI_HASH('C', 'D', 'I'),  // Change Detail Information
    X12_SEGMENT_CDS = EDI_HASH('C', 'D', 'S'),  // Case Description
    X12_SEGMENT_CED = EDI_HASH('C', 'E', 'D'),  // Administration of Justice Event Description
    X12_SEGMENT_CER = EDI_HASH('C', 'E', 'R'),  // Certification
    X12_SEGMENT_CF1 = EDI_HASH('C', 'F', '1'),  // Beginning Segment for Summary Freight Bill Manifest
    X12_SEGMENT_CF2 = EDI_HASH('C', 'F', '2'),  // Summary Freight Bill Detail
    X12_SEGMENT_CFI = EDI_HASH('C', 'F', 'I'),  // Compensation Financial Information
    X12_SEGMENT_CFT = EDI_HASH('C', 'F', 'T'),  // Cost Reporting Format Type
    X12_SEGMENT_CGS = EDI_HASH('C', 'G', 'S'),  // Charge
    X12_SEGMENT_CHB = EDI_HASH('C', 'H', 'B'),  // Chargeback Information
    X12_SEGMENT_CHR = EDI_HASH('C', 'H', 'R'),  // Car Hire Rates
    X12_SEGMENT_CI  = EDI_HASH('C', 'I', NIL),  // Carrier Interchange Agreement
    X12_SEGMENT_CIC = EDI_HASH('C', 'I', 'C'),  // Car Information Control
    X12_SEGMENT_CID = EDI_HASH('C', 'I', 'D'),  // Characteristic/Class ID
    X12_SEGMENT_CII = EDI_HASH('C', 'I', 'I'),  // Conveyance Insurance Information
    X12_SEGMENT_CIV = EDI_HASH('C', 'I', 'V'),  // Civil Action Liability
    X12_SEGMENT_CL1 = EDI_HASH('C', 'L', '1'),  // Claim Codes
    X12_SEGMENT_CLD = EDI_HASH('C', 'L', 'D'),  // Load Detail
    X12_SEGMENT_CLI = EDI_HASH('C', 'L', 'I'),  // Cost Line Item
    X12_SEGMENT_CLM = EDI_HASH('C', 'L', 'M'),  // Health Claim
    X12_SEGMENT_CLP = EDI_HASH('C', 'L', 'P'),  // Claim Level Data
    X12_SEGMENT_CLR = EDI_HASH('C', 'L', 'R'),  // Car Location Routing Request
    X12_SEGMENT_CM  = EDI_HASH('C', 'M', NIL),  // Cargo Manifest
    X12_SEGMENT_CMA = EDI_HASH('C', 'M', 'A'),  // Cooperative Market Agreement
    X12_SEGMENT_CMC = EDI_HASH('C', 'M', 'C'),  // Commodity Classification
    X12_SEGMENT_CN1 = EDI_HASH('C', 'N', '1'),  // Contract Information
    X12_SEGMENT_COB = EDI_HASH('C', 'O', 'B'),  // Coordination of Benefits
    X12_SEGMENT_COD = EDI_HASH('C', 'O', 'D'),  // Channel of Distribution
    X12_SEGMENT_COI = EDI_HASH('C', 'O', 'I'),  // Container Information
    X12_SEGMENT_COM = EDI_HASH('C', 'O', 'M'),  // Communication Contact Information
    X12_SEGMENT_CON = EDI_HASH('C', 'O', 'N'),  // Contract Number Detail
    X12_SEGMENT_CPI = EDI_HASH('C', 'P', 'I'),  // Claimant Payment Information
    X12_SEGMENT_CPL = EDI_HASH('C', 'P', 'L'),  // Program Information
    X12_SEGMENT_CPM = EDI_HASH('C', 'P', 'M'),  // Customs Profile Management Information
    X12_SEGMENT_CPR = EDI_HASH('C', 'P', 'R'),  // Commodity Price Reference
    X12_SEGMENT_CQ  = EDI_HASH('C', 'Q', NIL),  // Credentials and Qualifications
    X12_SEGMENT_CR1 = EDI_HASH('C', 'R', '1'),  // Ambulance Certification
    X12_SEGMENT_CR2 = EDI_HASH('C', 'R', '2'),  // Chiropractic Certification
    X12_SEGMENT_CR3 = EDI_HASH('C', 'R', '3'),  // Durable Medical Equipment Certification
    X12_SEGMENT_CR4 = EDI_HASH('C', 'R', '4'),  // Enteral or Parenteral Therapy Certification
    X12_SEGMENT_CR5 = EDI_HASH('C', 'R', '5'),  // Oxygen Therapy Certification
    X12_SEGMENT_CR6 = EDI_HASH('C', 'R', '6'),  // Home Health Care Certification
    X12_SEGMENT_CR7 = EDI_HASH('C', 'R', '7'),  // Home Health Treatment Plan Certification
    X12_SEGMENT_CR8 = EDI_HASH('C', 'R', '8'),  // Implant Certification
    X12_SEGMENT_CRC = EDI_HASH('C', 'R', 'C'),  // Conditions Indicator
    X12_SEGMENT_CRD = EDI_HASH('C', 'R', 'D'),  // Content Reporting Detail
    X12_SEGMENT_CRI = EDI_HASH('C', 'R', 'I'),  // Claim Report Information
    X12_SEGMENT_CRO = EDI_HASH('C', 'R', 'O'),  // Credit Report Order Details
    X12_SEGMENT_CRS = EDI_HASH('C', 'R', 'S'),  // Course Record
    X12_SEGMENT_CRT = EDI_HASH('C', 'R', 'T'),  // Contractor Report Type
    X12_SEGMENT_CS  = EDI_HASH('C', 'S', NIL),  // Contract Summary
    X12_SEGMENT_CSB = EDI_HASH('C', 'S', 'B'),  // Cryptographic Service Message Body
    X12_SEGMENT_CSC = EDI_HASH('C', 'S', 'C'),  // Cryptographic Service Message Certificates and Keys
    X12_SEGMENT_CSD = EDI_HASH('C', 'S', 'D'),  // Consolidated Shipment Invoice Data
    X12_SEGMENT_CSE = EDI_HASH('C', 'S', 'E'),  // Educational Course Information
    X12_SEGMENT_CSF = EDI_HASH('C', 'S', 'F'),  // Conditional Sampling Frequency
    X12_SEGMENT_CSH = EDI_HASH('C', 'S', 'H'),  // Sales Requirements
    X12_SEGMENT_CSI = EDI_HASH('C', 'S', 'I'),  // Claim Status Information
    X12_SEGMENT_CSM = EDI_HASH('C', 'S', 'M'),  // Cryptographic Service Message Header
    X12_SEGMENT_CSS = EDI_HASH('C', 'S', 'S'),  // Conditional Sampling Sequence
    X12_SEGMENT_CST = EDI_HASH('C', 'S', 'T'),  // Cost Analysis
    X12_SEGMENT_CSU = EDI_HASH('C', 'S', 'U'),  // Supplemental Course Data
    X12_SEGMENT_CT  = EDI_HASH('C', 'T', NIL),  // Car Type
    X12_SEGMENT_CTB = EDI_HASH('C', 'T', 'B'),  // Restrictions/Conditions
    X12_SEGMENT_CTC = EDI_HASH('C', 'T', 'C'),  // Car Hire Transaction Control
    X12_SEGMENT_CTH = EDI_HASH('C', 'T', 'H'),  // Beginning Segment for Contract Transaction Set
    X12_SEGMENT_CTP = EDI_HASH('C', 'T', 'P'),  // Pricing Information
    X12_SEGMENT_CTT = EDI_HASH('C', 'T', 'T'),  // Transaction Totals
    X12_SEGMENT_CTX = EDI_HASH('C', 'T', 'X'),  // Context
    X12_SEGMENT_CUR = EDI_HASH('C', 'U', 'R'),  // Currency
    X12_SEGMENT_CV  = EDI_HASH('C', 'V', NIL),  // Cycle/Summary Value
    X12_SEGMENT_CYC = EDI_HASH('C', 'Y', 'C'),  // Car Hire Cycle
    X12_SEGMENT_D9  = EDI_HASH('D', '9', NIL),  // Destination Station
    X12_SEGMENT_DAD = EDI_HASH('D', 'A', 'D'),  // Debit Authorization Detail
    X12_SEGMENT_DAI = EDI_HASH('D', 'A', 'I'),  // Appendix Information
    X12_SEGMENT_DAM = EDI_HASH('D', 'A', 'M'),  // Damage Information
    X12_SEGMENT_DB  = EDI_HASH('D', 'B', NIL),  // Disbursement Information
    X12_SEGMENT_DD  = EDI_HASH('D', 'D', NIL),  // Demand Detail
    X12_SEGMENT_DDI = EDI_HASH('D', 'D', 'I'),  // Explanation
    X12_SEGMENT_DED = EDI_HASH('D', 'E', 'D'),  // Deductions
    X12_SEGMENT_DEF = EDI_HASH('D', 'E', 'F'),  // Delayed Repayment
    X12_SEGMENT_DEG = EDI_HASH('D', 'E', 'G'),  // Degree Record
    X12_SEGMENT_DEL = EDI_HASH('D', 'E', 'L'),  // Delivery Logistics
    X12_SEGMENT_DEP = EDI_HASH('D', 'E', 'P'),  // Deposit
    X12_SEGMENT_DET = EDI_HASH('D', 'E', 'T'),  // Diet Information
    X12_SEGMENT_DEX = EDI_HASH('D', 'E', 'X'),  // Delivery Execution Information
    X12_SEGMENT_DFI = EDI_HASH('D', 'F', 'I'),  // Default Information
    X12_SEGMENT_DH  = EDI_HASH('D', 'H', NIL),  // Dealer Hours
    X12_SEGMENT_DIS = EDI_HASH('D', 'I', 'S'),  // Discount Detail
    X12_SEGMENT_DK  = EDI_HASH('D', 'K', NIL),  // Docket Header
    X12_SEGMENT_DL  = EDI_HASH('D', 'L', NIL),  // Auto Claim Detail - Labor
    X12_SEGMENT_DLP = EDI_HASH('D', 'L', 'P'),  // Delivery Parameter
    X12_SEGMENT_DLV = EDI_HASH('D', 'L', 'V'),  // Deliverable Information
    X12_SEGMENT_DM  = EDI_HASH('D', 'M', NIL),  // Demurrage/Detention/ Storage Rate
    X12_SEGMENT_DMA = EDI_HASH('D', 'M', 'A'),  // Additional Demographic Information
    X12_SEGMENT_DMG = EDI_HASH('D', 'M', 'G'),  // Demographic Information
    X12_SEGMENT_DMI = EDI_HASH('D', 'M', 'I'),  // Data Maintenance Information
    X12_SEGMENT_DN  = EDI_HASH('D', 'N', NIL),  // Dealer Effectivity
    X12_SEGMENT_DN1 = EDI_HASH('D', 'N', '1'),  // Orthodontic Information
    X12_SEGMENT_DN2 = EDI_HASH('D', 'N', '2'),  // Tooth Summary
    X12_SEGMENT_DOS = EDI_HASH('D', 'O', 'S'),  // Definition of Share
    X12_SEGMENT_DP  = EDI_HASH('D', 'P', NIL),  // Auto Claim Detail - Parts
    X12_SEGMENT_DPN = EDI_HASH('D', 'P', 'N'),  // Dependent Information
    X12_SEGMENT_DR  = EDI_HASH('D', 'R', NIL),  // Docket Range
    X12_SEGMENT_DRA = EDI_HASH('D', 'R', 'A'),  // Drug Authorization
    X12_SEGMENT_DRT = EDI_HASH('D', 'R', 'T'),  // Car Hire Rate Detail
    X12_SEGMENT_DSB = EDI_HASH('D', 'S', 'B'),  // Disability Information
    X12_SEGMENT_DTM = EDI_HASH('D', 'T', 'M'),  // Date/Time Reference
    X12_SEGMENT_DTP = EDI_HASH('D', 'T', 'P'),  // Date or Time or Period
    X12_SEGMENT_DVI = EDI_HASH('D', 'V', 'I'),  // Dynamic Vehicle Information
    X12_SEGMENT_E01 = EDI_HASH('E', '0', '1'),  // Electronic Form Main Heading
    X12_SEGMENT_E03 = EDI_HASH('E', '0', '3'),  // Interchange Order of Segments
    X12_SEGMENT_E1  = EDI_HASH('E', '1', NIL),  // Empty Car Disposition - Pended Destination Consignee
    X12_SEGMENT_E10 = EDI_HASH('E', '1', '0'),  // Transaction Set Grouping
    X12_SEGMENT_E13 = EDI_HASH('E', '1', '3'),  // Segment Order in Transaction Set
    X12_SEGMENT_E20 = EDI_HASH('E', '2', '0'),  // Segment Header Information
    X12_SEGMENT_E22 = EDI_HASH('E', '2', '2'),  // Data Element Relationships in a Segment or Composite
    X12_SEGMENT_E24 = EDI_HASH('E', '2', '4'),  // Data Element Sequence in a Segment or Composite
    X12_SEGMENT_E30 = EDI_HASH('E', '3', '0'),  // Data Element Attributes
    X12_SEGMENT_E34 = EDI_HASH('E', '3', '4'),  // Code List Values for a Data Element
    X12_SEGMENT_E4  = EDI_HASH('E', '4', NIL),  // Empty Car Disposition - Pended Destination City
    X12_SEGMENT_E40 = EDI_HASH('E', '4', '0'),  // EDI Standards Note Reference
    X12_SEGMENT_E41 = EDI_HASH('E', '4', '1'),  // Composite Header Information
    X12_SEGMENT_E5  = EDI_HASH('E', '5', NIL),  // Empty Car Disposition - Pended Destination Route
    X12_SEGMENT_E6  = EDI_HASH('E', '6', NIL),  // Advance Car Disposition
    X12_SEGMENT_E8  = EDI_HASH('E', '8', NIL),  // Blocking and Response Information
    X12_SEGMENT_EA  = EDI_HASH('E', 'A', NIL),  // Equipment Attributes
    X12_SEGMENT_EB  = EDI_HASH('E', 'B', NIL),  // Eligibility or Benefit Information
    X12_SEGMENT_EC  = EDI_HASH('E', 'C', NIL),  // Employment Class
    X12_SEGMENT_ECS = EDI_HASH('E', 'C', 'S'),  // Fees and Payment Schedule
    X12_SEGMENT_ED  = EDI_HASH('E', 'D', NIL),  // Equipment Description
    X12_SEGMENT_EDF = EDI_HASH('E', 'D', 'F'),  // Educational Fee Information
    X12_SEGMENT_EFI = EDI_HASH('E', 'F', 'I'),  // Electronic Format Identification
    X12_SEGMENT_EI  = EDI_HASH('E', 'I', NIL),  // Automatic Equipment Identification
    X12_SEGMENT_EIA = EDI_HASH('E', 'I', 'A'),  // Beginning Segment for Equipment Inquiry or Advice
    X12_SEGMENT_ELV = EDI_HASH('E', 'L', 'V'),  // Employee Leave Summary
    X12_SEGMENT_EM  = EDI_HASH('E', 'M', NIL),  // Equipment Characteristics
    X12_SEGMENT_EMP = EDI_HASH('E', 'M', 'P'),  // Employer
    X12_SEGMENT_EMS = EDI_HASH('E', 'M', 'S'),  // Employment Position
    X12_SEGMENT_EMT = EDI_HASH('E', 'M', 'T'),  // Employment
    X12_SEGMENT_ENE = EDI_HASH('E', 'N', 'E'),  // Electronic Systems Environment
    X12_SEGMENT_ENM = EDI_HASH('E', 'N', 'M'),  // School Enrollment Data
    X12_SEGMENT_ENR = EDI_HASH('E', 'N', 'R'),  // School Enrollment Information
    X12_SEGMENT_ENT = EDI_HASH('E', 'N', 'T'),  // Entity
    X12_SEGMENT_EQ  = EDI_HASH('E', 'Q', NIL),  // Eligibility or Benefit Inquiry
    X12_SEGMENT_EQD = EDI_HASH('E', 'Q', 'D'),  // EQD Equipment Damage Information
    X12_SEGMENT_ER  = EDI_HASH('E', 'R', NIL),  // Rail Event Reporting
    X12_SEGMENT_ERI = EDI_HASH('E', 'R', 'I'),  // Entity Relationship
    X12_SEGMENT_ERP = EDI_HASH('E', 'R', 'P'),  // Educational Record Purpose
    X12_SEGMENT_ES  = EDI_HASH('E', 'S', NIL),  // Equipment Status
    X12_SEGMENT_ESI = EDI_HASH('E', 'S', 'I'),  // Employment Status Information
    X12_SEGMENT_ETD = EDI_HASH('E', 'T', 'D'),  // Excess Transportation Detail
    X12_SEGMENT_EXI = EDI_HASH('E', 'X', 'I'),  // Excavation Ticket Information
    X12_SEGMENT_F01 = EDI_HASH('F', '0', '1'),  // Identification of Claim (Claimant Originated)
    X12_SEGMENT_F02 = EDI_HASH('F', '0', '2'),  // Identification of Shipment
    X12_SEGMENT_F04 = EDI_HASH('F', '0', '4'),  // Weight/Volume Loss
    X12_SEGMENT_F05 = EDI_HASH('F', '0', '5'),  // Allowance/Charge (Claim)
    X12_SEGMENT_F07 = EDI_HASH('F', '0', '7'),  // Auto Claim Detail
    X12_SEGMENT_F09 = EDI_HASH('F', '0', '9'),  // Detail - Supporting Evidence for Claim
    X12_SEGMENT_F10 = EDI_HASH('F', '1', '0'),  // Identification of Claim (Tracer)
    X12_SEGMENT_F11 = EDI_HASH('F', '1', '1'),  // Status
    X12_SEGMENT_F12 = EDI_HASH('F', '1', '2'),  // Basic Claim Information - Automotive
    X12_SEGMENT_F13 = EDI_HASH('F', '1', '3'),  // Payment Information
    X12_SEGMENT_F14 = EDI_HASH('F', '1', '4'),  // Line Item Reject
    X12_SEGMENT_F6X = EDI_HASH('F', '6', 'X'),  // Identification (Automotive)
    X12_SEGMENT_F9  = EDI_HASH('F', '9', NIL),  // Origin Station
    X12_SEGMENT_FA1 = EDI_HASH('F', 'A', '1'),  // Type of Financial Accounting Data
    X12_SEGMENT_FA2 = EDI_HASH('F', 'A', '2'),  // Accounting Data
    X12_SEGMENT_FAA = EDI_HASH('F', 'A', 'A'),  // Financial Asset Account
    X12_SEGMENT_FAC = EDI_HASH('F', 'A', 'C'),  // Facing Direction
    X12_SEGMENT_FBB = EDI_HASH('F', 'B', 'B'),  // Foreign and Industry Business
    X12_SEGMENT_FC  = EDI_HASH('F', 'C', NIL),  // Financial Contribution
    X12_SEGMENT_FCL = EDI_HASH('F', 'C', 'L'),  // Foreclosure
    X12_SEGMENT_FDA = EDI_HASH('F', 'D', 'A'),  // Facility Description
    X12_SEGMENT_FGS = EDI_HASH('F', 'G', 'S'),  // Form Group
    X12_SEGMENT_FH  = EDI_HASH('F', 'H', NIL),  // Family History
    X12_SEGMENT_FIR = EDI_HASH('F', 'I', 'R'),  // Financial Information
    X12_SEGMENT_FIS = EDI_HASH('F', 'I', 'S'),  // Mortgage Loan Fiscal Data
    X12_SEGMENT_FK  = EDI_HASH('F', 'K', NIL),  // Factor
    X12_SEGMENT_FNA = EDI_HASH('F', 'N', 'A'),  // Financial Status Information
    X12_SEGMENT_FOB = EDI_HASH('F', 'O', 'B'),  // F.O.B. Related Instructions
    X12_SEGMENT_FOS = EDI_HASH('F', 'O', 'S'),  // Field of Study
    X12_SEGMENT_FPT = EDI_HASH('F', 'P', 'T'),  // Financial Participation
    X12_SEGMENT_FQR = EDI_HASH('F', 'Q', 'R'),  // Forecast Parameters
    X12_SEGMENT_FRM = EDI_HASH('F', 'R', 'M'),  // Supporting Documentation
    X12_SEGMENT_FSA = EDI_HASH('F', 'S', 'A'),  // Tax Advantage Account
    X12_SEGMENT_FST = EDI_HASH('F', 'S', 'T'),  // Forecast Schedule
    X12_SEGMENT_FTH = EDI_HASH('F', 'T', 'H'),  // First Time Home Buyer
    X12_SEGMENT_FU1 = EDI_HASH('F', 'U', '1'),  // Bracket Information
    X12_SEGMENT_FU2 = EDI_HASH('F', 'U', '2'),  // Deal Value
    X12_SEGMENT_FU3 = EDI_HASH('F', 'U', '3'),  // Product Detail
    X12_SEGMENT_FU4 = EDI_HASH('F', 'U', '4'),  // Product Pack Detail
    X12_SEGMENT_FU5 = EDI_HASH('F', 'U', '5'),  // Co-Product Information
    X12_SEGMENT_FX2 = EDI_HASH('F', 'X', '2'),  // Product Classification
    X12_SEGMENT_FX3 = EDI_HASH('F', 'X', '3'),  // Product Information
    X12_SEGMENT_FX4 = EDI_HASH('F', 'X', '4'),  // Equipment Information
    X12_SEGMENT_FX5 = EDI_HASH('F', 'X', '5'),  // Services Information
    X12_SEGMENT_FX6 = EDI_HASH('F', 'X', '6'),  // Brand Label
    X12_SEGMENT_FX7 = EDI_HASH('F', 'X', '7'),  // Pack and Size
    X12_SEGMENT_G01 = EDI_HASH('G', '0', '1'),  // Invoice Identification
    X12_SEGMENT_G05 = EDI_HASH('G', '0', '5'),  // Total Shipment Information
    X12_SEGMENT_G07 = EDI_HASH('G', '0', '7'),  // Carrier Information
    X12_SEGMENT_G08 = EDI_HASH('G', '0', '8'),  // Pallet Receipt Disposition
    X12_SEGMENT_G1  = EDI_HASH('G', '1', NIL),  // Shipment Type Information
    X12_SEGMENT_G11 = EDI_HASH('G', '1', '1'),  // Coupon Reporting Specifications
    X12_SEGMENT_G12 = EDI_HASH('G', '1', '2'),  // Coupon Physical Characteristics
    X12_SEGMENT_G13 = EDI_HASH('G', '1', '3'),  // Store Size Attributes
    X12_SEGMENT_G14 = EDI_HASH('G', '1', '4'),  // Coupon Special Processing
    X12_SEGMENT_G15 = EDI_HASH('G', '1', '5'),  // Coupon Distribution
    X12_SEGMENT_G17 = EDI_HASH('G', '1', '7'),  // Item Detail - Invoice
    X12_SEGMENT_G18 = EDI_HASH('G', '1', '8'),  // Store Category Size
    X12_SEGMENT_G19 = EDI_HASH('G', '1', '9'),  // Line Item Detail - Quantity/Unit of Measure/Price Differences
    X12_SEGMENT_G2  = EDI_HASH('G', '2', NIL),  // Beyond Routing
    X12_SEGMENT_G20 = EDI_HASH('G', '2', '0'),  // Item Packing Detail
    X12_SEGMENT_G21 = EDI_HASH('G', '2', '1'),  // Product Information
    X12_SEGMENT_G22 = EDI_HASH('G', '2', '2'),  // Pre-Pricing Information
    X12_SEGMENT_G23 = EDI_HASH('G', '2', '3'),  // Terms of Sale
    X12_SEGMENT_G24 = EDI_HASH('G', '2', '4'),  // Promotion Reference
    X12_SEGMENT_G25 = EDI_HASH('G', '2', '5'),  // F.O.B. Information
    X12_SEGMENT_G26 = EDI_HASH('G', '2', '6'),  // Pricing Conditions
    X12_SEGMENT_G28 = EDI_HASH('G', '2', '8'),  // Line Item Numbers
    X12_SEGMENT_G29 = EDI_HASH('G', '2', '9'),  // Store Display Information
    X12_SEGMENT_G3  = EDI_HASH('G', '3', NIL),  // Compensation Information
    X12_SEGMENT_G30 = EDI_HASH('G', '3', '0'),  // Retail Account Marketing Types
    X12_SEGMENT_G31 = EDI_HASH('G', '3', '1'),  // Total Invoice Quantity
    X12_SEGMENT_G32 = EDI_HASH('G', '3', '2'),  // Survey Question Response
    X12_SEGMENT_G33 = EDI_HASH('G', '3', '3'),  // Total Dollars Summary
    X12_SEGMENT_G35 = EDI_HASH('G', '3', '5'),  // Advertising Feature Information
    X12_SEGMENT_G36 = EDI_HASH('G', '3', '6'),  // Price List Reference
    X12_SEGMENT_G37 = EDI_HASH('G', '3', '7'),  // Labor Activity
    X12_SEGMENT_G38 = EDI_HASH('G', '3', '8'),  // Claim Payment Information
    X12_SEGMENT_G39 = EDI_HASH('G', '3', '9'),  // Item Characteristics - Vendor's Selling Unit
    X12_SEGMENT_G4  = EDI_HASH('G', '4', NIL),  // Scale Identification
    X12_SEGMENT_G40 = EDI_HASH('G', '4', '0'),  // Bracket Price
    X12_SEGMENT_G42 = EDI_HASH('G', '4', '2'),  // Promotion Announcement Identification
    X12_SEGMENT_G43 = EDI_HASH('G', '4', '3'),  // Promotion/Price List Area
    X12_SEGMENT_G45 = EDI_HASH('G', '4', '5'),  // Line Item Detail - Promotion
    X12_SEGMENT_G46 = EDI_HASH('G', '4', '6'),  // Promotion Allowance/Charge
    X12_SEGMENT_G47 = EDI_HASH('G', '4', '7'),  // Statement Identification
    X12_SEGMENT_G48 = EDI_HASH('G', '4', '8'),  // Statement/Invoice Identification
    X12_SEGMENT_G49 = EDI_HASH('G', '4', '9'),  // Statement Total
    X12_SEGMENT_G5  = EDI_HASH('G', '5', NIL),  // Scale Information
    X12_SEGMENT_G50 = EDI_HASH('G', '5', '0'),  // Purchase Order Identification
    X12_SEGMENT_G51 = EDI_HASH('G', '5', '1'),  // Free Goods/Product Condition
    X12_SEGMENT_G53 = EDI_HASH('G', '5', '3'),  // Maintenance Type
    X12_SEGMENT_G54 = EDI_HASH('G', '5', '4'),  // Module Description
    X12_SEGMENT_G55 = EDI_HASH('G', '5', '5'),  // Item Characteristics - Consumer Unit
    X12_SEGMENT_G61 = EDI_HASH('G', '6', '1'),  // Contact
    X12_SEGMENT_G62 = EDI_HASH('G', '6', '2'),  // Date/Time
    X12_SEGMENT_G63 = EDI_HASH('G', '6', '3'),  // Period
    X12_SEGMENT_G66 = EDI_HASH('G', '6', '6'),  // Transportation Instructions
    X12_SEGMENT_G68 = EDI_HASH('G', '6', '8'),  // Line Item Detail - Product
    X12_SEGMENT_G69 = EDI_HASH('G', '6', '9'),  // Line Item Detail - Description
    X12_SEGMENT_G70 = EDI_HASH('G', '7', '0'),  // Line Item Detail - Miscellaneous
    X12_SEGMENT_G72 = EDI_HASH('G', '7', '2'),  // Allowance or Charge
    X12_SEGMENT_G73 = EDI_HASH('G', '7', '3'),  // Allowance or Charge Description
    X12_SEGMENT_G76 = EDI_HASH('G', '7', '6'),  // Total Purchase Order
    X12_SEGMENT_G82 = EDI_HASH('G', '8', '2'),  // Delivery/Return Base Record Identifier
    X12_SEGMENT_G83 = EDI_HASH('G', '8', '3'),  // Line Item Detail/Direct Store Delivery
    X12_SEGMENT_G84 = EDI_HASH('G', '8', '4'),  // Delivery/Return Record of Totals
    X12_SEGMENT_G85 = EDI_HASH('G', '8', '5'),  // Record Integrity Check
    X12_SEGMENT_G86 = EDI_HASH('G', '8', '6'),  // Signature Identification
    X12_SEGMENT_G87 = EDI_HASH('G', '8', '7'),  // Delivery/Return Adjustment Identification
    X12_SEGMENT_G88 = EDI_HASH('G', '8', '8'),  // Delivery/Return Identification Adjustment
    X12_SEGMENT_G89 = EDI_HASH('G', '8', '9'),  // Line Item Detail - Adjustment
    X12_SEGMENT_G91 = EDI_HASH('G', '9', '1'),  // Price Change Status
    X12_SEGMENT_G92 = EDI_HASH('G', '9', '2'),  // Purchase Order Change Type
    X12_SEGMENT_G93 = EDI_HASH('G', '9', '3'),  // Price Bracket Identification
    X12_SEGMENT_G94 = EDI_HASH('G', '9', '4'),  // Promotion Conditions
    X12_SEGMENT_G95 = EDI_HASH('G', '9', '5'),  // Performance Requirements
    X12_SEGMENT_GA  = EDI_HASH('G', 'A', NIL),  // Canadian Grain Information
    X12_SEGMENT_GDP = EDI_HASH('G', 'D', 'P'),  // General Dosing Parameters
    X12_SEGMENT_GE  = EDI_HASH('G', 'E', NIL),  // Functional Group Trailer
    X12_SEGMENT_GF  = EDI_HASH('G', 'F', NIL),  // Furnished Goods and Services
    X12_SEGMENT_GH  = EDI_HASH('G', 'H', NIL),  // Group Header
    X12_SEGMENT_GID = EDI_HASH('G', 'I', 'D'),  // Group Identification
    X12_SEGMENT_GR  = EDI_HASH('G', 'R', NIL),  // Guarantee Result Detail
    X12_SEGMENT_GR2 = EDI_HASH('G', 'R', '2'),  // Train Data
    X12_SEGMENT_GR4 = EDI_HASH('G', 'R', '4'),  // Loading Cluster
    X12_SEGMENT_GR5 = EDI_HASH('G', 'R', '5'),  // Loading Details
    X12_SEGMENT_GRI = EDI_HASH('G', 'R', 'I'),  // Statistical Government Information
    X12_SEGMENT_GRP = EDI_HASH('G', 'R', 'P'),  // Group Dosage Parameters
    X12_SEGMENT_GS  = EDI_HASH('G', 'S', NIL),  // Functional Group Header
    X12_SEGMENT_GY  = EDI_HASH('G', 'Y', NIL),  // Geography
    X12_SEGMENT_H1  = EDI_HASH('H', '1', NIL),  // Hazardous Material
    X12_SEGMENT_H2  = EDI_HASH('H', '2', NIL),  // Additional Hazardous Material Description
    X12_SEGMENT_H3  = EDI_HASH('H', '3', NIL),  // Special Handling Instructions
    X12_SEGMENT_H5  = EDI_HASH('H', '5', NIL),  // Car Service Order
    X12_SEGMENT_H6  = EDI_HASH('H', '6', NIL),  // Special Services
    X12_SEGMENT_HAD = EDI_HASH('H', 'A', 'D'),  // Hospital Affiliation Detail
    X12_SEGMENT_HC  = EDI_HASH('H', 'C', NIL),  // Health Condition
    X12_SEGMENT_HCP = EDI_HASH('H', 'C', 'P'),  // Health Care Pricing
    X12_SEGMENT_HCR = EDI_HASH('H', 'C', 'R'),  // Health Care Services Review
    X12_SEGMENT_HD  = EDI_HASH('H', 'D', NIL),  // Health Coverage
    X12_SEGMENT_HI  = EDI_HASH('H', 'I', NIL),  // Health Care Information Codes
    X12_SEGMENT_HL  = EDI_HASH('H', 'L', NIL),  // Hierarchical Level
    X12_SEGMENT_HLH = EDI_HASH('H', 'L', 'H'),  // Health Information
    X12_SEGMENT_HPL = EDI_HASH('H', 'P', 'L'),  // Health Care Provider License
    X12_SEGMENT_HS  = EDI_HASH('H', 'S', NIL),  // Health Screening
    X12_SEGMENT_HSD = EDI_HASH('H', 'S', 'D'),  // Health Care Services Delivery
    X12_SEGMENT_IA  = EDI_HASH('I', 'A', NIL),  // Interconnect Mailbag Acknowledgment
    X12_SEGMENT_IC  = EDI_HASH('I', 'C', NIL),  // Intermodal Chassis Equipment
    X12_SEGMENT_ICH = EDI_HASH('I', 'C', 'H'),  // Individual Characteristics
    X12_SEGMENT_ICM = EDI_HASH('I', 'C', 'M'),  // Individual Income
    X12_SEGMENT_ID  = EDI_HASH('I', 'D', NIL),  // Inspection Detail Segment
    X12_SEGMENT_ID1 = EDI_HASH('I', 'D', '1'),  // Item Detail Dimensions
    X12_SEGMENT_ID2 = EDI_HASH('I', 'D', '2'),  // Item Image Detail
    X12_SEGMENT_ID3 = EDI_HASH('I', 'D', '3'),  // Dimensions Detail
    X12_SEGMENT_ID4 = EDI_HASH('I', 'D', '4'),  // Load Details
    X12_SEGMENT_IDB = EDI_HASH('I', 'D', 'B'),  // Indebtedness for Student Loans
    X12_SEGMENT_IDC = EDI_HASH('I', 'D', 'C'),  // Identification Card
    X12_SEGMENT_IEA = EDI_HASH('I', 'E', 'A'),  // Interchange Control Trailer
    X12_SEGMENT_IGI = EDI_HASH('I', 'G', 'I'),  // Insurer or Guarantor Information
    X12_SEGMENT_IH  = EDI_HASH('I', 'H', NIL),  // Interconnect Mailbag Header
    X12_SEGMENT_III = EDI_HASH('I', 'I', 'I'),  // Information
    X12_SEGMENT_IIS = EDI_HASH('I', 'I', 'S'),  // Interchange Identification Segment
    X12_SEGMENT_IK3 = EDI_HASH('I', 'K', '3'),  // Implementation Data Segment Note
    X12_SEGMENT_IK4 = EDI_HASH('I', 'K', '4'),  // Implementation Data Element Note
    X12_SEGMENT_IK5 = EDI_HASH('I', 'K', '5'),  // Implementation Transaction Set Response Trailer
    X12_SEGMENT_IM  = EDI_HASH('I', 'M', NIL),  // Intermodal Movement Information
    X12_SEGMENT_IMA = EDI_HASH('I', 'M', 'A'),  // Interchange Move Authority
    X12_SEGMENT_IMC = EDI_HASH('I', 'M', 'C'),  // Interconnect Mailbag Client Exchange Header
    X12_SEGMENT_IMM = EDI_HASH('I', 'M', 'M'),  // Immunization Status
    X12_SEGMENT_IMP = EDI_HASH('I', 'M', 'P'),  // Impairment Detail
    X12_SEGMENT_IN1 = EDI_HASH('I', 'N', '1'),  // Individual Identification
    X12_SEGMENT_IN2 = EDI_HASH('I', 'N', '2'),  // Individual Name Structure Components
    X12_SEGMENT_INC = EDI_HASH('I', 'N', 'C'),  // Installment Information
    X12_SEGMENT_IND = EDI_HASH('I', 'N', 'D'),  // Additional Individual Demographic Information
    X12_SEGMENT_ING = EDI_HASH('I', 'N', 'G'),  // Ingredients
    X12_SEGMENT_INI = EDI_HASH('I', 'N', 'I'),  // Incorporation Information
    X12_SEGMENT_INQ = EDI_HASH('I', 'N', 'Q'),  // Credit Inquiry Details
    X12_SEGMENT_INR = EDI_HASH('I', 'N', 'R'),  // Information Request
    X12_SEGMENT_INS = EDI_HASH('I', 'N', 'S'),  // Insured Benefit
    X12_SEGMENT_INT = EDI_HASH('I', 'N', 'T'),  // Interest
    X12_SEGMENT_INV = EDI_HASH('I', 'N', 'V'),  // Investment Vehicle Selection
    X12_SEGMENT_INX = EDI_HASH('I', 'N', 'X'),  // Index Detail
    X12_SEGMENT_IRA = EDI_HASH('I', 'R', 'A'),  // Investor Reporting Action
    X12_SEGMENT_IRP = EDI_HASH('I', 'R', 'P'),  // Report Selection Segment
    X12_SEGMENT_IS1 = EDI_HASH('I', 'S', '1'),  // Estimated Time of Arrival and Car Scheduling
    X12_SEGMENT_IS2 = EDI_HASH('I', 'S', '2'),  // Scheduled Events
    X12_SEGMENT_ISA = EDI_HASH('I', 'S', 'A'),  // Interchange Control Header
    X12_SEGMENT_ISB = EDI_HASH('I', 'S', 'B'),  // Grade of Service Request Segment
    X12_SEGMENT_ISC = EDI_HASH('I', 'S', 'C'),  // Interline Service Commitment Detail
    X12_SEGMENT_ISD = EDI_HASH('I', 'S', 'D'),  // Railroad Interline Service Definition Detail
    X12_SEGMENT_ISE = EDI_HASH('I', 'S', 'E'),  // Deferred Delivery Request Segment
    X12_SEGMENT_ISI = EDI_HASH('I', 'S', 'I'),  // Institutional Staff Information
    X12_SEGMENT_ISR = EDI_HASH('I', 'S', 'R'),  // Item Status Report
    X12_SEGMENT_ISS = EDI_HASH('I', 'S', 'S'),  // Invoice Shipment Summary
    X12_SEGMENT_ISX = EDI_HASH('I', 'S', 'X'),  // Interchange Syntax Extension
    X12_SEGMENT_IT  = EDI_HASH('I', 'T', NIL),  // Interconnect Mailbag Trailer
    X12_SEGMENT_IT1 = EDI_HASH('I', 'T', '1'),  // Baseline Item Data (Invoice)
    X12_SEGMENT_IT3 = EDI_HASH('I', 'T', '3'),  // Additional Item Data
    X12_SEGMENT_IT8 = EDI_HASH('I', 'T', '8'),  // Conditions of Sale
    X12_SEGMENT_ITA = EDI_HASH('I', 'T', 'A'),  // Allowance, Charge or Service
    X12_SEGMENT_ITC = EDI_HASH('I', 'T', 'C'),  // Information Type and Comment Results
    X12_SEGMENT_ITD = EDI_HASH('I', 'T', 'D'),  // Terms of Sale/Deferred Terms of Sale
    X12_SEGMENT_ITS = EDI_HASH('I', 'T', 'S'),  // Item Selection
    X12_SEGMENT_IV1 = EDI_HASH('I', 'V', '1'),  // Lane Estimates
    X12_SEGMENT_IVT = EDI_HASH('I', 'V', 'T'),  // Inventory Parameters
    X12_SEGMENT_JCT = EDI_HASH('J', 'C', 'T'),  // Railroad Junction Information
    X12_SEGMENT_JID = EDI_HASH('J', 'I', 'D'),  // Equipment Detail
    X12_SEGMENT_JIL = EDI_HASH('J', 'I', 'L'),  // Line Item Detail for the Operating Expense Statement
    X12_SEGMENT_JIT = EDI_HASH('J', 'I', 'T'),  // Just-In-Time Schedule
    X12_SEGMENT_JL  = EDI_HASH('J', 'L', NIL),  // Journal Identification
    X12_SEGMENT_JS  = EDI_HASH('J', 'S', NIL),  // Rail Junction Settlement Role Information
    X12_SEGMENT_K1  = EDI_HASH('K', '1', NIL),  // Remarks
    X12_SEGMENT_K2  = EDI_HASH('K', '2', NIL),  // Administrative Message
    X12_SEGMENT_K3  = EDI_HASH('K', '3', NIL),  // File Information
    X12_SEGMENT_L0  = EDI_HASH('L', '0', NIL),  // Line Item - Quantity and Weight
    X12_SEGMENT_L1  = EDI_HASH('L', '1', NIL),  // Rate and Charges
    X12_SEGMENT_L10 = EDI_HASH('L', '1', '0'),  // Weight Information
    X12_SEGMENT_L11 = EDI_HASH('L', '1', '1'),  // Business Instructions and Reference Number
    X12_SEGMENT_L12 = EDI_HASH('L', '1', '2'),  // Alternate Lading Description
    X12_SEGMENT_L13 = EDI_HASH('L', '1', '3'),  // Commodity Details
    X12_SEGMENT_L1A = EDI_HASH('L', '1', 'A'),  // Billing Identification
    X12_SEGMENT_L3  = EDI_HASH('L', '3', NIL),  // Total Weight and Charges
    X12_SEGMENT_L4  = EDI_HASH('L', '4', NIL),  // Measurement
    X12_SEGMENT_L5  = EDI_HASH('L', '5', NIL),  // Description, Marks and Numbers
    X12_SEGMENT_L7  = EDI_HASH('L', '7', NIL),  // Tariff Reference
    X12_SEGMENT_L8  = EDI_HASH('L', '8', NIL),  // Line Item Subtotal
    X12_SEGMENT_L9  = EDI_HASH('L', '9', NIL),  // Charge Detail
    X12_SEGMENT_LAD = EDI_HASH('L', 'A', 'D'),  // Lading Detail
    X12_SEGMENT_LC  = EDI_HASH('L', 'C', NIL),  // Life Coverage
    X12_SEGMENT_LC1 = EDI_HASH('L', 'C', '1'),  // Lane Commitments
    X12_SEGMENT_LCD = EDI_HASH('L', 'C', 'D'),  // Place/Location Description
    X12_SEGMENT_LCT = EDI_HASH('L', 'C', 'T'),  // Logistics Container Tracking Information
    X12_SEGMENT_LDT = EDI_HASH('L', 'D', 'T'),  // Lead Time
    X12_SEGMENT_LE  = EDI_HASH('L', 'E', NIL),  // Loop Trailer
    X12_SEGMENT_LEP = EDI_HASH('L', 'E', 'P'),  // EPA Required Data
    X12_SEGMENT_LEQ = EDI_HASH('L', 'E', 'Q'),  // Leased Equipment Information
    X12_SEGMENT_LET = EDI_HASH('L', 'E', 'T'),  // Load and Equipment Type
    X12_SEGMENT_LFG = EDI_HASH('L', 'F', 'G'),  // Hazardous Information, Finished Goods
    X12_SEGMENT_LFH = EDI_HASH('L', 'F', 'H'),  // Free-form Hazardous Material Information
    X12_SEGMENT_LFI = EDI_HASH('L', 'F', 'I'),  // Beginning Segment for Locomotive Information
    X12_SEGMENT_LH  = EDI_HASH('L', 'H', NIL),  // Mixed Hazardous Commodities
    X12_SEGMENT_LH1 = EDI_HASH('L', 'H', '1'),  // Hazardous Identification Information
    X12_SEGMENT_LH2 = EDI_HASH('L', 'H', '2'),  // Hazardous Classification Information
    X12_SEGMENT_LH3 = EDI_HASH('L', 'H', '3'),  // Hazardous Material Shipping Name Information
    X12_SEGMENT_LH4 = EDI_HASH('L', 'H', '4'),  // Canadian Dangerous Requirements
    X12_SEGMENT_LH6 = EDI_HASH('L', 'H', '6'),  // Hazardous Certification
    X12_SEGMENT_LHE = EDI_HASH('L', 'H', 'E'),  // Empty Equipment Hazardous Material Information
    X12_SEGMENT_LHR = EDI_HASH('L', 'H', 'R'),  // Hazardous Material Identifying Reference Numbers
    X12_SEGMENT_LHT = EDI_HASH('L', 'H', 'T'),  // Transborder Hazardous Requirements
    X12_SEGMENT_LIC = EDI_HASH('L', 'I', 'C'),  // License Information
    X12_SEGMENT_LID = EDI_HASH('L', 'I', 'D'),  // Loss Information Description
    X12_SEGMENT_LIE = EDI_HASH('L', 'I', 'E'),  // Individual or Event Location
    X12_SEGMENT_LIN = EDI_HASH('L', 'I', 'N'),  // Item Identification
    X12_SEGMENT_LM  = EDI_HASH('L', 'M', NIL),  // Code Source Information
    X12_SEGMENT_LN  = EDI_HASH('L', 'N', NIL),  // Loan Information
    X12_SEGMENT_LN1 = EDI_HASH('L', 'N', '1'),  // Loan Specific Data
    X12_SEGMENT_LN2 = EDI_HASH('L', 'N', '2'),  // Existing Real Estate Loan Specific Data
    X12_SEGMENT_LOC = EDI_HASH('L', 'O', 'C'),  // Location
    X12_SEGMENT_LOD = EDI_HASH('L', 'O', 'D'),  // Location Description
    X12_SEGMENT_LP  = EDI_HASH('L', 'P', NIL),  // Load Planning
    X12_SEGMENT_LQ  = EDI_HASH('L', 'Q', NIL),  // Industry Code Identification
    X12_SEGMENT_LRQ = EDI_HASH('L', 'R', 'Q'),  // Mortgage Characteristics Requested
    X12_SEGMENT_LS  = EDI_HASH('L', 'S', NIL),  // Loop Header
    X12_SEGMENT_LS1 = EDI_HASH('L', 'S', '1'),  // Asset Item Identification
    X12_SEGMENT_LSC = EDI_HASH('L', 'S', 'C'),  // Location Scope Parameter
    X12_SEGMENT_LT  = EDI_HASH('L', 'T', NIL),  // Letter of Recommendation
    X12_SEGMENT_LTE = EDI_HASH('L', 'T', 'E'),  // Letter of Recommendation Evaluation
    X12_SEGMENT_LTR = EDI_HASH('L', 'T', 'R'),  // Laboratory Test Results
    X12_SEGMENT_LUC = EDI_HASH('L', 'U', 'C'),  // Loan Underwriting
    X12_SEGMENT_LUI = EDI_HASH('L', 'U', 'I'),  // Language Use
    X12_SEGMENT_LV  = EDI_HASH('L', 'V', NIL),  // Loan Verification
    X12_SEGMENT_LX  = EDI_HASH('L', 'X', NIL),  // Transaction Set Line Number
    X12_SEGMENT_M0  = EDI_HASH('M', '0', NIL),  // Letter of Credit Reference
    X12_SEGMENT_M1  = EDI_HASH('M', '1', NIL),  // Insurance
    X12_SEGMENT_M10 = EDI_HASH('M', '1', '0'),  // Manifest Identifying Information
    X12_SEGMENT_M11 = EDI_HASH('M', '1', '1'),  // Manifest Bill of Lading Details
    X12_SEGMENT_M12 = EDI_HASH('M', '1', '2'),  // In-bond Identifying Information
    X12_SEGMENT_M13 = EDI_HASH('M', '1', '3'),  // Manifest Amendment Details
    X12_SEGMENT_M14 = EDI_HASH('M', '1', '4'),  // General Order Status Information
    X12_SEGMENT_M15 = EDI_HASH('M', '1', '5'),  // Customs Events Advisory Details
    X12_SEGMENT_M2  = EDI_HASH('M', '2', NIL),  // Sales/Delivery Terms
    X12_SEGMENT_M20 = EDI_HASH('M', '2', '0'),  // Permit to Transfer Request Details
    X12_SEGMENT_M21 = EDI_HASH('M', '2', '1'),  // Supplementary In-Bond Information
    X12_SEGMENT_M3  = EDI_HASH('M', '3', NIL),  // Release
    X12_SEGMENT_M7  = EDI_HASH('M', '7', NIL),  // Seal Numbers
    X12_SEGMENT_M7A = EDI_HASH('M', '7', 'A'),  // Seal Number Replacement
    X12_SEGMENT_MAN = EDI_HASH('M', 'A', 'N'),  // Marks and Numbers Information
    X12_SEGMENT_MBL = EDI_HASH('M', 'B', 'L'),  // Bill of Lading
    X12_SEGMENT_MC  = EDI_HASH('M', 'C', NIL),  // Miscellaneous and Accessorial Charges
    X12_SEGMENT_MCD = EDI_HASH('M', 'C', 'D'),  // Mortgage Closing Data
    X12_SEGMENT_MCT = EDI_HASH('M', 'C', 'T'),  // Tariff Accessorial Charges
    X12_SEGMENT_MEA = EDI_HASH('M', 'E', 'A'),  // Measurements
    X12_SEGMENT_MI  = EDI_HASH('M', 'I', NIL),  // Media Information
    X12_SEGMENT_MI1 = EDI_HASH('M', 'I', '1'),  // Mileage Source
    X12_SEGMENT_MIA = EDI_HASH('M', 'I', 'A'),  // Inpatient Adjudication
    X12_SEGMENT_MIC = EDI_HASH('M', 'I', 'C'),  // Mortgage Insurance Coverage
    X12_SEGMENT_MIR = EDI_HASH('M', 'I', 'R'),  // Mortgage Insurance Response
    X12_SEGMENT_MIS = EDI_HASH('M', 'I', 'S'),  // Mortgagee Information Status
    X12_SEGMENT_MIT = EDI_HASH('M', 'I', 'T'),  // Message Identification
    X12_SEGMENT_MKS = EDI_HASH('M', 'K', 'S'),  // Marks Awarded
    X12_SEGMENT_MLA = EDI_HASH('M', 'L', 'A'),  // Mortgage Loan Audit Information
    X12_SEGMENT_MLS = EDI_HASH('M', 'L', 'S'),  // Milestone
    X12_SEGMENT_MNC = EDI_HASH('M', 'N', 'C'),  // Mortgage Note Characteristics
    X12_SEGMENT_MOA = EDI_HASH('M', 'O', 'A'),  // Outpatient Adjudication
    X12_SEGMENT_MPI = EDI_HASH('M', 'P', 'I'),  // Military Personnel Information
    X12_SEGMENT_MPP = EDI_HASH('M', 'P', 'P'),  // Mortgage Pool Program
    X12_SEGMENT_MRC = EDI_HASH('M', 'R', 'C'),  // Mortgagor Response Characteristics
    X12_SEGMENT_MS1 = EDI_HASH('M', 'S', '1'),  // Equipment, Shipment, or Real Property Location
    X12_SEGMENT_MS2 = EDI_HASH('M', 'S', '2'),  // Equipment or Container Owner and Type
    X12_SEGMENT_MS3 = EDI_HASH('M', 'S', '3'),  // Interline Information
    X12_SEGMENT_MS4 = EDI_HASH('M', 'S', '4'),  // Shipment or Package Dimensions
    X12_SEGMENT_MS5 = EDI_HASH('M', 'S', '5'),  // Shipment Rates and Charges
    X12_SEGMENT_MS6 = EDI_HASH('M', 'S', '6'),  // Shipment Quantity and Weight
    X12_SEGMENT_MSG = EDI_HASH('M', 'S', 'G'),  // Message Text
    X12_SEGMENT_MSI = EDI_HASH('M', 'S', 'I'),  // Multi-stop Shipment Information
    X12_SEGMENT_MSS = EDI_HASH('M', 'S', 'S'),  // Material Safety Data Sheet Section Information
    X12_SEGMENT_MTX = EDI_HASH('M', 'T', 'X'),  // Text
    X12_SEGMENT_N1  = EDI_HASH('N', '1', NIL),  // Party Identification
    X12_SEGMENT_N10 = EDI_HASH('N', '1', '0'),  // Quantity and Description
    X12_SEGMENT_N11 = EDI_HASH('N', '1', '1'),  // Store Location
    X12_SEGMENT_N12 = EDI_HASH('N', '1', '2'),  // Equipment Environment
    X12_SEGMENT_N2  = EDI_HASH('N', '2', NIL),  // Additional Name Information
    X12_SEGMENT_N21 = EDI_HASH('N', '2', '1'),  // Equipment Registration Details
    X12_SEGMENT_N3  = EDI_HASH('N', '3', NIL),  // Party Location
    X12_SEGMENT_N4  = EDI_HASH('N', '4', NIL),  // Geographic Location
    X12_SEGMENT_N5  = EDI_HASH('N', '5', NIL),  // Equipment Ordered
    X12_SEGMENT_N7  = EDI_HASH('N', '7', NIL),  // Equipment Details
    X12_SEGMENT_N7A = EDI_HASH('N', '7', 'A'),  // Accessorial Equipment Details
    X12_SEGMENT_N7B = EDI_HASH('N', '7', 'B'),  // Additional Equipment Details
    X12_SEGMENT_N8  = EDI_HASH('N', '8', NIL),  // Waybill Reference
    X12_SEGMENT_N8A = EDI_HASH('N', '8', 'A'),  // Additional Reference Information
    X12_SEGMENT_N9  = EDI_HASH('N', '9', NIL),  // Extended Reference Information
    X12_SEGMENT_NA  = EDI_HASH('N', 'A', NIL),  // Cross-Reference Equipment
    X12_SEGMENT_NCA = EDI_HASH('N', 'C', 'A'),  // Nonconformance Action
    X12_SEGMENT_NCD = EDI_HASH('N', 'C', 'D'),  // Nonconformance Description
    X12_SEGMENT_NF1 = EDI_HASH('N', 'F', '1'),  // Nutrition Facts Panel
    X12_SEGMENT_NF2 = EDI_HASH('N', 'F', '2'),  // Serving Size Statement
    X12_SEGMENT_NF3 = EDI_HASH('N', 'F', '3'),  // Servings Per Container Statement
    X12_SEGMENT_NF4 = EDI_HASH('N', 'F', '4'),  // Nutrition Facts Panel Calorie
    X12_SEGMENT_NF5 = EDI_HASH('N', 'F', '5'),  // Nutrition Facts Panel Fats
    X12_SEGMENT_NF6 = EDI_HASH('N', 'F', '6'),  // Nutrition Facts Panel Carbohydrates
    X12_SEGMENT_NF7 = EDI_HASH('N', 'F', '7'),  // Nutrition Facts Panel Other Nutrients
    X12_SEGMENT_NF8 = EDI_HASH('N', 'F', '8'),  // Nutrition Facts Panel Vitamins and Minerals
    X12_SEGMENT_NFB = EDI_HASH('N', 'F', 'B'),  // Nutrition Facts Panel Footer Calorie Diet
    X12_SEGMENT_NFC = EDI_HASH('N', 'F', 'C'),  // Nutrition Facts Panel Footer Calorie Diet Nutrient Amounts
    X12_SEGMENT_NFD = EDI_HASH('N', 'F', 'D'),  // Nutrition Facts Panel Footer Statement
    X12_SEGMENT_NFE = EDI_HASH('N', 'F', 'E'),  // Nutrition Facts Panel Product Name
    X12_SEGMENT_NM1 = EDI_HASH('N', 'M', '1'),  // Individual or Organizational Name
    X12_SEGMENT_NTE = EDI_HASH('N', 'T', 'E'),  // Note/Special Instruction
    X12_SEGMENT_NX1 = EDI_HASH('N', 'X', '1'),  // Property or Entity Identification
    X12_SEGMENT_NX2 = EDI_HASH('N', 'X', '2'),  // Location ID Component
    X12_SEGMENT_OBI = EDI_HASH('O', 'B', 'I'),  // Obligation Information
    X12_SEGMENT_OD  = EDI_HASH('O', 'D', NIL),  // Origin and Destination
    X12_SEGMENT_OI  = EDI_HASH('O', 'I', NIL),  // Other Health Insurance Information
    X12_SEGMENT_OID = EDI_HASH('O', 'I', 'D'),  // Order Information Detail
    X12_SEGMENT_OOI = EDI_HASH('O', 'O', 'I'),  // Associated Object Type Identification
    X12_SEGMENT_OPS = EDI_HASH('O', 'P', 'S'),  // Program Subject Area and Eligibility
    X12_SEGMENT_OPX = EDI_HASH('O', 'P', 'X'),  // Placement Criteria
    X12_SEGMENT_OQS = EDI_HASH('O', 'Q', 'S'),  // Order Quantity Sequence
    X12_SEGMENT_ORI = EDI_HASH('O', 'R', 'I'),  // Object Reference Identification
    X12_SEGMENT_OTI = EDI_HASH('O', 'T', 'I'),  // Original Transaction Identification
    X12_SEGMENT_P1  = EDI_HASH('P', '1', NIL),  // Pickup
    X12_SEGMENT_P2  = EDI_HASH('P', '2', NIL),  // Delivery Date Information
    X12_SEGMENT_P4  = EDI_HASH('P', '4', NIL),  // Port Information
    X12_SEGMENT_P5  = EDI_HASH('P', '5', NIL),  // Port Function
    X12_SEGMENT_PAD = EDI_HASH('P', 'A', 'D'),  // Product Adjustment Detail
    X12_SEGMENT_PAI = EDI_HASH('P', 'A', 'I'),  // Print Advertisement Information
    X12_SEGMENT_PAL = EDI_HASH('P', 'A', 'L'),  // Pallet Type and Load Characteristics
    X12_SEGMENT_PAM = EDI_HASH('P', 'A', 'M'),  // Period Amount
    X12_SEGMENT_PAS = EDI_HASH('P', 'A', 'S'),  // Property Appraisal Summary
    X12_SEGMENT_PAT = EDI_HASH('P', 'A', 'T'),  // Patient Information
    X12_SEGMENT_PBI = EDI_HASH('P', 'B', 'I'),  // Problem Identification
    X12_SEGMENT_PCL = EDI_HASH('P', 'C', 'L'),  // Previous College
    X12_SEGMENT_PCR = EDI_HASH('P', 'C', 'R'),  // Payment Cancellation Request
    X12_SEGMENT_PCS = EDI_HASH('P', 'C', 'S'),  // Product Claim Status
    X12_SEGMENT_PCT = EDI_HASH('P', 'C', 'T'),  // Percent Amounts
    X12_SEGMENT_PD  = EDI_HASH('P', 'D', NIL),  // Pricing Data
    X12_SEGMENT_PDD = EDI_HASH('P', 'D', 'D'),  // Pricing Data Detail
    X12_SEGMENT_PDE = EDI_HASH('P', 'D', 'E'),  // Property Metes and Bounds Description
    X12_SEGMENT_PDH = EDI_HASH('P', 'D', 'H'),  // Pharmaceutical Drug Information
    X12_SEGMENT_PDI = EDI_HASH('P', 'D', 'I'),  // Practice Detail Information
    X12_SEGMENT_PDL = EDI_HASH('P', 'D', 'L'),  // Payment Details
    X12_SEGMENT_PDP = EDI_HASH('P', 'D', 'P'),  // Property Description - Personal
    X12_SEGMENT_PDR = EDI_HASH('P', 'D', 'R'),  // Property Description - Real
    X12_SEGMENT_PDS = EDI_HASH('P', 'D', 'S'),  // Property Description/Legal Description
    X12_SEGMENT_PEN = EDI_HASH('P', 'E', 'N'),  // Pension Information
    X12_SEGMENT_PER = EDI_HASH('P', 'E', 'R'),  // Administrative Communications Contact
    X12_SEGMENT_PEX = EDI_HASH('P', 'E', 'X'),  // Property or Housing Expense
    X12_SEGMENT_PI  = EDI_HASH('P', 'I', NIL),  // Price Authority Identification
    X12_SEGMENT_PID = EDI_HASH('P', 'I', 'D'),  // Product/Item Description
    X12_SEGMENT_PIN = EDI_HASH('P', 'I', 'N'),  // Previous Incident
    X12_SEGMENT_PKD = EDI_HASH('P', 'K', 'D'),  // Packaging Description
    X12_SEGMENT_PKG = EDI_HASH('P', 'K', 'G'),  // Marking, Packaging, Loading
    X12_SEGMENT_PKL = EDI_HASH('P', 'K', 'L'),  // Multi-Pack Configuration
    X12_SEGMENT_PL  = EDI_HASH('P', 'L', NIL),  // Proposal Cost Logic
    X12_SEGMENT_PLA = EDI_HASH('P', 'L', 'A'),  // Place or Location
    X12_SEGMENT_PLB = EDI_HASH('P', 'L', 'B'),  // Provider Level Adjustment
    X12_SEGMENT_PLC = EDI_HASH('P', 'L', 'C'),  // Equipment Placement Information
    X12_SEGMENT_PLD = EDI_HASH('P', 'L', 'D'),  // Pallet Shipment Information
    X12_SEGMENT_PLI = EDI_HASH('P', 'L', 'I'),  // Previous Loan Information
    X12_SEGMENT_PM  = EDI_HASH('P', 'M', NIL),  // Electronic Funds Transfer Information
    X12_SEGMENT_PMP = EDI_HASH('P', 'M', 'P'),  // Performance Measures
    X12_SEGMENT_PO1 = EDI_HASH('P', 'O', '1'),  // Baseline Item Data
    X12_SEGMENT_PO3 = EDI_HASH('P', 'O', '3'),  // Additional Item Detail
    X12_SEGMENT_PO4 = EDI_HASH('P', 'O', '4'),  // Item Physical Details
    X12_SEGMENT_PO5 = EDI_HASH('P', 'O', '5'),  // Expanded Item Physical Details
    X12_SEGMENT_PO6 = EDI_HASH('P', 'O', '6'),  // Non-Packaged Item Physcial Details
    X12_SEGMENT_PO7 = EDI_HASH('P', 'O', '7'),  // Gift Container Physical Details
    X12_SEGMENT_PO8 = EDI_HASH('P', 'O', '8'),  // Unmarked Trade Item Physical Details
    X12_SEGMENT_POC = EDI_HASH('P', 'O', 'C'),  // Line Item Change
    X12_SEGMENT_POD = EDI_HASH('P', 'O', 'D'),  // Proof of Delivery
    X12_SEGMENT_PPA = EDI_HASH('P', 'P', 'A'),  // Property Location
    X12_SEGMENT_PPD = EDI_HASH('P', 'P', 'D'),  // Payment Pattern Details
    X12_SEGMENT_PPL = EDI_HASH('P', 'P', 'L'),  // Price Support Data
    X12_SEGMENT_PPR = EDI_HASH('P', 'P', 'R'),  // Contract Party Restriction
    X12_SEGMENT_PPY = EDI_HASH('P', 'P', 'Y'),  // Personal Property Description
    X12_SEGMENT_PR  = EDI_HASH('P', 'R', NIL),  // Product (Commodity)
    X12_SEGMENT_PR1 = EDI_HASH('P', 'R', '1'),  // Price Request Parameter List 1
    X12_SEGMENT_PR2 = EDI_HASH('P', 'R', '2'),  // Price Request Parameter List 2
    X12_SEGMENT_PRC = EDI_HASH('P', 'R', 'C'),  // Payment Rate Change
    X12_SEGMENT_PRD = EDI_HASH('P', 'R', 'D'),  // Mortgage Loan Product Description
    X12_SEGMENT_PRF = EDI_HASH('P', 'R', 'F'),  // Purchase Order Reference
    X12_SEGMENT_PRI = EDI_HASH('P', 'R', 'I'),  // External Reference Identifier
    X12_SEGMENT_PRJ = EDI_HASH('P', 'R', 'J'),  // Multifamily Housing Project
    X12_SEGMENT_PRM = EDI_HASH('P', 'R', 'M'),  // Basic Trace Parameters
    X12_SEGMENT_PRR = EDI_HASH('P', 'R', 'R'),  // Problem Report
    X12_SEGMENT_PRS = EDI_HASH('P', 'R', 'S'),  // Part Release Status
    X12_SEGMENT_PRT = EDI_HASH('P', 'R', 'T'),  // Part Disposition
    X12_SEGMENT_PRV = EDI_HASH('P', 'R', 'V'),  // Provider Information
    X12_SEGMENT_PS  = EDI_HASH('P', 'S', NIL),  // Protective Service Instructions
    X12_SEGMENT_PS1 = EDI_HASH('P', 'S', '1'),  // Purchase Service
    X12_SEGMENT_PSA = EDI_HASH('P', 'S', 'A'),  // Partner Share Accounting
    X12_SEGMENT_PSC = EDI_HASH('P', 'S', 'C'),  // Product Service Contract
    X12_SEGMENT_PSD = EDI_HASH('P', 'S', 'D'),  // Physical Sample Description
    X12_SEGMENT_PSG = EDI_HASH('P', 'S', 'G'),  // Program Spend
    X12_SEGMENT_PT  = EDI_HASH('P', 'T', NIL),  // Patron
    X12_SEGMENT_PTD = EDI_HASH('P', 'T', 'D'),  // Product Transfer and Resale Detail
    X12_SEGMENT_PTF = EDI_HASH('P', 'T', 'F'),  // Property Transaction Financials
    X12_SEGMENT_PTS = EDI_HASH('P', 'T', 'S'),  // Property Tax Status
    X12_SEGMENT_PUN = EDI_HASH('P', 'U', 'N'),  // Beginning Segment for Motor Carrier Pickup Notification
    X12_SEGMENT_PWK = EDI_HASH('P', 'W', 'K'),  // Paperwork
    X12_SEGMENT_PYD = EDI_HASH('P', 'Y', 'D'),  // Payroll Deduction
    X12_SEGMENT_PYM = EDI_HASH('P', 'Y', 'M'),  // Payment Manner and Percentage
    X12_SEGMENT_PYT = EDI_HASH('P', 'Y', 'T'),  // Historical Payment Terms
    X12_SEGMENT_Q2  = EDI_HASH('Q', '2', NIL),  // Status Details (Ocean)
    X12_SEGMENT_Q3  = EDI_HASH('Q', '3', NIL),  // Arrival Details
    X12_SEGMENT_Q5  = EDI_HASH('Q', '5', NIL),  // Status Details
    X12_SEGMENT_Q7  = EDI_HASH('Q', '7', NIL),  // Lading Exception Status
    X12_SEGMENT_Q8  = EDI_HASH('Q', '8', NIL),  // Detail Delivery Exception Information
    X12_SEGMENT_QTY = EDI_HASH('Q', 'T', 'Y'),  // Quantity Information
    X12_SEGMENT_R1  = EDI_HASH('R', '1', NIL),  // Route Information (Air)
    X12_SEGMENT_R11 = EDI_HASH('R', '1', '1'),  // Beginning Segment for Trailer or Container Repair Billing
    X12_SEGMENT_R12 = EDI_HASH('R', '1', '2'),  // Work Order Information
    X12_SEGMENT_R13 = EDI_HASH('R', '1', '3'),  // Line Item Repair
    X12_SEGMENT_R2  = EDI_HASH('R', '2', NIL),  // Route Information
    X12_SEGMENT_R2A = EDI_HASH('R', '2', 'A'),  // Route Information with Preference
    X12_SEGMENT_R2B = EDI_HASH('R', '2', 'B'),  // Junctions and Proportions
    X12_SEGMENT_R2C = EDI_HASH('R', '2', 'C'),  // Division Basis
    X12_SEGMENT_R2D = EDI_HASH('R', '2', 'D'),  // Miscellaneous Charge
    X12_SEGMENT_R3  = EDI_HASH('R', '3', NIL),  // Route Information - Motor
    X12_SEGMENT_R4  = EDI_HASH('R', '4', NIL),  // Port or Terminal
    X12_SEGMENT_R9  = EDI_HASH('R', '9', NIL),  // Route Code Identification
    X12_SEGMENT_RA  = EDI_HASH('R', 'A', NIL),  // Rate Header
    X12_SEGMENT_RAB = EDI_HASH('R', 'A', 'B'),  // Rate or Minimum Qualifiers
    X12_SEGMENT_RAP = EDI_HASH('R', 'A', 'P'),  // Requirement, Attribute, and Proficiency
    X12_SEGMENT_RAS = EDI_HASH('R', 'A', 'S'),  // Reason Adjustment
    X12_SEGMENT_RC  = EDI_HASH('R', 'C', NIL),  // Root Cause
    X12_SEGMENT_RCD = EDI_HASH('R', 'C', 'D'),  // Receiving Conditions
    X12_SEGMENT_RCR = EDI_HASH('R', 'C', 'R'),  // Reporting Criteria
    X12_SEGMENT_RD  = EDI_HASH('R', 'D', NIL),  // Rate Data
    X12_SEGMENT_RDD = EDI_HASH('R', 'D', 'D'),  // Route Description Detail
    X12_SEGMENT_RDI = EDI_HASH('R', 'D', 'I'),  // Retail Account Demographic Information
    X12_SEGMENT_RDM = EDI_HASH('R', 'D', 'M'),  // Remittance Delivery Method
    X12_SEGMENT_RDR = EDI_HASH('R', 'D', 'R'),  // Return Disposition Reason
    X12_SEGMENT_RDT = EDI_HASH('R', 'D', 'T'),  // Revision Date/Time
    X12_SEGMENT_REA = EDI_HASH('R', 'E', 'A'),  // Real Estate Property Information
    X12_SEGMENT_REC = EDI_HASH('R', 'E', 'C'),  // Real Estate Condition
    X12_SEGMENT_RED = EDI_HASH('R', 'E', 'D'),  // Related Data
    X12_SEGMENT_REF = EDI_HASH('R', 'E', 'F'),  // Reference Information
    X12_SEGMENT_REG = EDI_HASH('R', 'E', 'G'),  // Regulatory Application
    X12_SEGMENT_REL = EDI_HASH('R', 'E', 'L'),  // Relationship
    X12_SEGMENT_REN = EDI_HASH('R', 'E', 'N'),  // Rate Request Information
    X12_SEGMENT_REP = EDI_HASH('R', 'E', 'P'),  // Repair Action
    X12_SEGMENT_REQ = EDI_HASH('R', 'E', 'Q'),  // Request Information
    X12_SEGMENT_RES = EDI_HASH('R', 'E', 'S'),  // Real Estate Sales Price Change
    X12_SEGMENT_RET = EDI_HASH('R', 'E', 'T'),  // Real Estate Transaction
    X12_SEGMENT_RIC = EDI_HASH('R', 'I', 'C'),  // Financial Return
    X12_SEGMENT_RLD = EDI_HASH('R', 'L', 'D'),  // Down Payment Data
    X12_SEGMENT_RLT = EDI_HASH('R', 'L', 'T'),  // Real Estate Loan Type
    X12_SEGMENT_RMR = EDI_HASH('R', 'M', 'R'),  // Remittance Advice Accounts Receivable Open Item Reference
    X12_SEGMENT_RMT = EDI_HASH('R', 'M', 'T'),  // Remittance Advice
    X12_SEGMENT_RO  = EDI_HASH('R', 'O', NIL),  // Public Record or Obligation
    X12_SEGMENT_RP  = EDI_HASH('R', 'P', NIL),  // Retirement Product
    X12_SEGMENT_RPA = EDI_HASH('R', 'P', 'A'),  // Rate Amounts or Percents
    X12_SEGMENT_RQS = EDI_HASH('R', 'Q', 'S'),  // Request for Information
    X12_SEGMENT_RRA = EDI_HASH('R', 'R', 'A'),  // Required Response
    X12_SEGMENT_RRE = EDI_HASH('R', 'R', 'E'),  // Contract Related Error Reporting
    X12_SEGMENT_RS  = EDI_HASH('R', 'S', NIL),  // Rate Subset
    X12_SEGMENT_RSC = EDI_HASH('R', 'S', 'C'),  // Resource
    X12_SEGMENT_RSD = EDI_HASH('R', 'S', 'D'),  // Residency Information
    X12_SEGMENT_RST = EDI_HASH('R', 'S', 'T'),  // Carrier Restriction
    X12_SEGMENT_RT  = EDI_HASH('R', 'T', NIL),  // Rate Destination
    X12_SEGMENT_RT1 = EDI_HASH('R', 'T', '1'),  // Rate Detail
    X12_SEGMENT_RTE = EDI_HASH('R', 'T', 'E'),  // Rate Information
    X12_SEGMENT_RTT = EDI_HASH('R', 'T', 'T'),  // Freight Rate Information
    X12_SEGMENT_RU1 = EDI_HASH('R', 'U', '1'),  // Retirement Board Detail
    X12_SEGMENT_RU2 = EDI_HASH('R', 'U', '2'),  // Employing Carrier Response
    X12_SEGMENT_RU3 = EDI_HASH('R', 'U', '3'),  // Employing Carrier Claim Profile
    X12_SEGMENT_RYL = EDI_HASH('R', 'Y', 'L'),  // Royalty Payment
    X12_SEGMENT_S1  = EDI_HASH('S', '1', NIL),  // Stop-off Name
    X12_SEGMENT_S2  = EDI_HASH('S', '2', NIL),  // Stop-off Address
    X12_SEGMENT_S3A = EDI_HASH('S', '3', 'A'),  // Assurance Header Level 1
    X12_SEGMENT_S3E = EDI_HASH('S', '3', 'E'),  // Security Trailer Level 1
    X12_SEGMENT_S3S = EDI_HASH('S', '3', 'S'),  // Security Header Level 1
    X12_SEGMENT_S4A = EDI_HASH('S', '4', 'A'),  // Assurance Header Level 2
    X12_SEGMENT_S4E = EDI_HASH('S', '4', 'E'),  // Security Trailer Level 2
    X12_SEGMENT_S4S = EDI_HASH('S', '4', 'S'),  // Security Header Level 2
    X12_SEGMENT_S5  = EDI_HASH('S', '5', NIL),  // Stop-off Details
    X12_SEGMENT_S9  = EDI_HASH('S', '9', NIL),  // Stop-off Station
    X12_SEGMENT_SA  = EDI_HASH('S', 'A', NIL),  // Status Action
    X12_SEGMENT_SAC = EDI_HASH('S', 'A', 'C'),  // Service, Promotion, Allowance, or Charge Information
    X12_SEGMENT_SAD = EDI_HASH('S', 'A', 'D'),  // Student Award Detail
    X12_SEGMENT_SAL = EDI_HASH('S', 'A', 'L'),  // Salary Information
    X12_SEGMENT_SB  = EDI_HASH('S', 'B', NIL),  // Docket Level
    X12_SEGMENT_SBI = EDI_HASH('S', 'B', 'I'),  // Specific Benefit Information
    X12_SEGMENT_SBR = EDI_HASH('S', 'B', 'R'),  // Subscriber Information
    X12_SEGMENT_SBT = EDI_HASH('S', 'B', 'T'),  // Subtest
    X12_SEGMENT_SC  = EDI_HASH('S', 'C', NIL),  // Docket Sub-level
    X12_SEGMENT_SCA = EDI_HASH('S', 'C', 'A'),  // Statistical Category Analysis
    X12_SEGMENT_SCD = EDI_HASH('S', 'C', 'D'),  // Sales Commission Employee Detail
    X12_SEGMENT_SCH = EDI_HASH('S', 'C', 'H'),  // Line Item Schedule
    X12_SEGMENT_SCL = EDI_HASH('S', 'C', 'L'),  // Rate Basis/Scales
    X12_SEGMENT_SCM = EDI_HASH('S', 'C', 'M'),  // Credit Score Model
    X12_SEGMENT_SCN = EDI_HASH('S', 'C', 'N'),  // Beginning Segment for Cartage Work Assignment
    X12_SEGMENT_SCP = EDI_HASH('S', 'C', 'P'),  // Beginning Segment for a Cartage Work Assignment Response
    X12_SEGMENT_SCR = EDI_HASH('S', 'C', 'R'),  // Shipper's Car Ordered Rail
    X12_SEGMENT_SCS = EDI_HASH('S', 'C', 'S'),  // Credit Score
    X12_SEGMENT_SCT = EDI_HASH('S', 'C', 'T'),  // School Type
    X12_SEGMENT_SD1 = EDI_HASH('S', 'D', '1'),  // Safety Data
    X12_SEGMENT_SDP = EDI_HASH('S', 'D', 'P'),  // Ship/Delivery Pattern
    X12_SEGMENT_SDQ = EDI_HASH('S', 'D', 'Q'),  // Destination Quantity
    X12_SEGMENT_SE  = EDI_HASH('S', 'E', NIL),  // Transaction Set Trailer
    X12_SEGMENT_SEF = EDI_HASH('S', 'E', 'F'),  // Payment Handling
    X12_SEGMENT_SER = EDI_HASH('S', 'E', 'R'),  // Service Charges
    X12_SEGMENT_SES = EDI_HASH('S', 'E', 'S'),  // Academic Session Header
    X12_SEGMENT_SFC = EDI_HASH('S', 'F', 'C'),  // Storage Facility Characteristics
    X12_SEGMENT_SG  = EDI_HASH('S', 'G', NIL),  // Shipment Status
    X12_SEGMENT_SHD = EDI_HASH('S', 'H', 'D'),  // Shipment Detail
    X12_SEGMENT_SHI = EDI_HASH('S', 'H', 'I'),  // Security Holding Information
    X12_SEGMENT_SHP = EDI_HASH('S', 'H', 'P'),  // Shipped/Received Information
    X12_SEGMENT_SHR = EDI_HASH('S', 'H', 'R'),  // Railroad Interline Service Special Handling Restrictions
    X12_SEGMENT_SI  = EDI_HASH('S', 'I', NIL),  // Service Characteristic Identification
    X12_SEGMENT_SID = EDI_HASH('S', 'I', 'D'),  // Standard Transportation Commodity Code Identification
    X12_SEGMENT_SII = EDI_HASH('S', 'I', 'I'),  // Sales Item Information
    X12_SEGMENT_SIN = EDI_HASH('S', 'I', 'N'),  // Substance Use
    X12_SEGMENT_SL1 = EDI_HASH('S', 'L', '1'),  // Tariff Details
    X12_SEGMENT_SLA = EDI_HASH('S', 'L', 'A'),  // School Accreditation and Licensing
    X12_SEGMENT_SLI = EDI_HASH('S', 'L', 'I'),  // Specific Loan Information
    X12_SEGMENT_SLN = EDI_HASH('S', 'L', 'N'),  // Subline Item Detail
    X12_SEGMENT_SLS = EDI_HASH('S', 'L', 'S'),  // Sales Parameters
    X12_SEGMENT_SLV = EDI_HASH('S', 'L', 'V'),  // Service Level
    X12_SEGMENT_SMA = EDI_HASH('S', 'M', 'A'),  // Station Address
    X12_SEGMENT_SMB = EDI_HASH('S', 'M', 'B'),  // Beginning Segment for Railroad Station Master File
    X12_SEGMENT_SMD = EDI_HASH('S', 'M', 'D'),  // Consolidated Shipment Manifest Data
    X12_SEGMENT_SMO = EDI_HASH('S', 'M', 'O'),  // Operational Services
    X12_SEGMENT_SMR = EDI_HASH('S', 'M', 'R'),  // Cross Reference
    X12_SEGMENT_SMS = EDI_HASH('S', 'M', 'S'),  // Station Codes Segment
    X12_SEGMENT_SN1 = EDI_HASH('S', 'N', '1'),  // Item Detail (Shipment)
    X12_SEGMENT_SOI = EDI_HASH('S', 'O', 'I'),  // Source of Income
    X12_SEGMENT_SOM = EDI_HASH('S', 'O', 'M'),  // Status of Mortgage
    X12_SEGMENT_SP  = EDI_HASH('S', 'P', NIL),  // Special Program
    X12_SEGMENT_SPA = EDI_HASH('S', 'P', 'A'),  // Status of Product or Activity
    X12_SEGMENT_SPE = EDI_HASH('S', 'P', 'E'),  // Security Protocol Error
    X12_SEGMENT_SPI = EDI_HASH('S', 'P', 'I'),  // Specification Identifier
    X12_SEGMENT_SPK = EDI_HASH('S', 'P', 'K'),  // Specimen Kit Information
    X12_SEGMENT_SPR = EDI_HASH('S', 'P', 'R'),  // Supplier Rating
    X12_SEGMENT_SPS = EDI_HASH('S', 'P', 'S'),  // Sampling Parameters for Summary Statistics
    X12_SEGMENT_SPT = EDI_HASH('S', 'P', 'T'),  // Spirit and Liqueur Information
    X12_SEGMENT_SPY = EDI_HASH('S', 'P', 'Y'),  // Scope of Power of Attorney
    X12_SEGMENT_SR  = EDI_HASH('S', 'R', NIL),  // Requested Service Schedule
    X12_SEGMENT_SRE = EDI_HASH('S', 'R', 'E'),  // Test Scores
    X12_SEGMENT_SS  = EDI_HASH('S', 'S', NIL),  // Docket Control Status
    X12_SEGMENT_SSC = EDI_HASH('S', 'S', 'C'),  // Beginning Segment for Service Commitment Advice
    X12_SEGMENT_SSD = EDI_HASH('S', 'S', 'D'),  // Shipment Sort Segregate Data
    X12_SEGMENT_SSE = EDI_HASH('S', 'S', 'E'),  // Entry and Exit Information
    X12_SEGMENT_SSS = EDI_HASH('S', 'S', 'S'),  // Product Special Services
    X12_SEGMENT_SST = EDI_HASH('S', 'S', 'T'),  // Student Academic Status
    X12_SEGMENT_ST  = EDI_HASH('S', 'T', NIL),  // Transaction Set Header
    X12_SEGMENT_STA = EDI_HASH('S', 'T', 'A'),  // Statistics
    X12_SEGMENT_STC = EDI_HASH('S', 'T', 'C'),  // Status Information
    X12_SEGMENT_STP = EDI_HASH('S', 'T', 'P'),  // Study Parameters
    X12_SEGMENT_STS = EDI_HASH('S', 'T', 'S'),  // Interchange Status Segment
    X12_SEGMENT_SUM = EDI_HASH('S', 'U', 'M'),  // Academic Summary
    X12_SEGMENT_SUP = EDI_HASH('S', 'U', 'P'),  // Supplementary Information
    X12_SEGMENT_SV  = EDI_HASH('S', 'V', NIL),  // Service Description
    X12_SEGMENT_SV1 = EDI_HASH('S', 'V', '1'),  // Professional Service
    X12_SEGMENT_SV2 = EDI_HASH('S', 'V', '2'),  // Institutional Service
    X12_SEGMENT_SV3 = EDI_HASH('S', 'V', '3'),  // Dental Service
    X12_SEGMENT_SV4 = EDI_HASH('S', 'V', '4'),  // Drug Service
    X12_SEGMENT_SV5 = EDI_HASH('S', 'V', '5'),  // Durable Medical Equipment Service
    X12_SEGMENT_SV6 = EDI_HASH('S', 'V', '6'),  // Anesthesia Service
    X12_SEGMENT_SV7 = EDI_HASH('S', 'V', '7'),  // Drug Adjudication
    X12_SEGMENT_SVA = EDI_HASH('S', 'V', 'A'),  // Security Value
    X12_SEGMENT_SVC = EDI_HASH('S', 'V', 'C'),  // Service Information
    X12_SEGMENT_SVD = EDI_HASH('S', 'V', 'D'),  // Service Line Adjudication
    X12_SEGMENT_SW  = EDI_HASH('S', 'W', NIL),  // Switching Charges
    X12_SEGMENT_SWC = EDI_HASH('S', 'W', 'C'),  // Switching Conditions
    X12_SEGMENT_SWD = EDI_HASH('S', 'W', 'D'),  // Switching Details
    X12_SEGMENT_SWR = EDI_HASH('S', 'W', 'R'),  // Switching Rates
    X12_SEGMENT_T1  = EDI_HASH('T', '1', NIL),  // Transit Inbound Origin
    X12_SEGMENT_T2  = EDI_HASH('T', '2', NIL),  // Transit Inbound Lading
    X12_SEGMENT_T3  = EDI_HASH('T', '3', NIL),  // Transit Inbound Route
    X12_SEGMENT_T6  = EDI_HASH('T', '6', NIL),  // Transit Inbound Rates
    X12_SEGMENT_T8  = EDI_HASH('T', '8', NIL),  // Free-form Transit Data
    X12_SEGMENT_TA  = EDI_HASH('T', 'A', NIL),  // Tax Authority
    X12_SEGMENT_TA1 = EDI_HASH('T', 'A', '1'),  // Interchange Acknowledgment
    X12_SEGMENT_TA3 = EDI_HASH('T', 'A', '3'),  // Interchange Delivery Notice Segment
    X12_SEGMENT_TAR = EDI_HASH('T', 'A', 'R'),  // Target Market
    X12_SEGMENT_TAX = EDI_HASH('T', 'A', 'X'),  // Tax Reference
    X12_SEGMENT_TBI = EDI_HASH('T', 'B', 'I'),  // Trade Line Bureau Identifier
    X12_SEGMENT_TBP = EDI_HASH('T', 'B', 'P'),  // Frequency Basis
    X12_SEGMENT_TC2 = EDI_HASH('T', 'C', '2'),  // Commodity
    X12_SEGMENT_TCD = EDI_HASH('T', 'C', 'D'),  // Itemized Call Detail
    X12_SEGMENT_TD1 = EDI_HASH('T', 'D', '1'),  // Carrier Details (Quantity and Weight)
    X12_SEGMENT_TD3 = EDI_HASH('T', 'D', '3'),  // Carrier Details (Equipment)
    X12_SEGMENT_TD4 = EDI_HASH('T', 'D', '4'),  // Carrier Details (Special Handling, or Hazardous Materials, or Both)
    X12_SEGMENT_TD5 = EDI_HASH('T', 'D', '5'),  // Carrier Details (Routing Sequence/Transit Time)
    X12_SEGMENT_TDS = EDI_HASH('T', 'D', 'S'),  // Total Monetary Value Summary
    X12_SEGMENT_TDT = EDI_HASH('T', 'D', 'T'),  // Tax Delinquency Status
    X12_SEGMENT_TED = EDI_HASH('T', 'E', 'D'),  // Technical Error Description
    X12_SEGMENT_TEM = EDI_HASH('T', 'E', 'M'),  // Pickup Totals
    X12_SEGMENT_TER = EDI_HASH('T', 'E', 'R'),  // Territory
    X12_SEGMENT_TF  = EDI_HASH('T', 'F', NIL),  // Tariff Information
    X12_SEGMENT_TFR = EDI_HASH('T', 'F', 'R'),  // Tariff Restrictions
    X12_SEGMENT_TFS = EDI_HASH('T', 'F', 'S'),  // Tax Form
    X12_SEGMENT_THE = EDI_HASH('T', 'H', 'E'),  // Screen Theater Identification
    X12_SEGMENT_TI  = EDI_HASH('T', 'I', NIL),  // Transport Information
    X12_SEGMENT_TIA = EDI_HASH('T', 'I', 'A'),  // Tax Information and Amount
    X12_SEGMENT_TID = EDI_HASH('T', 'I', 'D'),  // Task Identification
    X12_SEGMENT_TII = EDI_HASH('T', 'I', 'I'),  // Tax Installment Information
    X12_SEGMENT_TIS = EDI_HASH('T', 'I', 'S'),  // Title Insurance Services
    X12_SEGMENT_TLN = EDI_HASH('T', 'L', 'N'),  // Tradeline
    X12_SEGMENT_TMD = EDI_HASH('T', 'M', 'D'),  // Test Method
    X12_SEGMENT_TOA = EDI_HASH('T', 'O', 'A'),  // Type of Activity
    X12_SEGMENT_TOO = EDI_HASH('T', 'O', 'O'),  // Tooth Identification
    X12_SEGMENT_TOV = EDI_HASH('T', 'O', 'V'),  // Vehicle Use Information
    X12_SEGMENT_TPB = EDI_HASH('T', 'P', 'B'),  // Business Professional Title
    X12_SEGMENT_TPD = EDI_HASH('T', 'P', 'D'),  // Trading Partner Detail
    X12_SEGMENT_TPP = EDI_HASH('T', 'P', 'P'),  // Third Party Payment
    X12_SEGMENT_TRD = EDI_HASH('T', 'R', 'D'),  // Trade Item Ingredient Details
    X12_SEGMENT_TRF = EDI_HASH('T', 'R', 'F'),  // Rating Factors
    X12_SEGMENT_TRL = EDI_HASH('T', 'R', 'L'),  // Equipment Usage Information
    X12_SEGMENT_TRN = EDI_HASH('T', 'R', 'N'),  // Trace
    X12_SEGMENT_TRS = EDI_HASH('T', 'R', 'S'),  // Tax Rate
    X12_SEGMENT_TRT = EDI_HASH('T', 'R', 'T'),  // Trade Item Type
    X12_SEGMENT_TS  = EDI_HASH('T', 'S', NIL),  // Tariff Section
    X12_SEGMENT_TS2 = EDI_HASH('T', 'S', '2'),  // Transaction Supplemental Statistics
    X12_SEGMENT_TS3 = EDI_HASH('T', 'S', '3'),  // Transaction Statistics
    X12_SEGMENT_TSD = EDI_HASH('T', 'S', 'D'),  // Trailer Shipment Details
    X12_SEGMENT_TSI = EDI_HASH('T', 'S', 'I'),  // Automatic Equipment Tag Status Information
    X12_SEGMENT_TSP = EDI_HASH('T', 'S', 'P'),  // Test Period or Interval
    X12_SEGMENT_TST = EDI_HASH('T', 'S', 'T'),  // Test Score Record
    X12_SEGMENT_TSU = EDI_HASH('T', 'S', 'U'),  // Transaction Summary
    X12_SEGMENT_TT  = EDI_HASH('T', 'T', NIL),  // Term Text
    X12_SEGMENT_TUD = EDI_HASH('T', 'U', 'D'),  // Trade Union Data
    X12_SEGMENT_TXI = EDI_HASH('T', 'X', 'I'),  // Tax Information
    X12_SEGMENT_TXN = EDI_HASH('T', 'X', 'N'),  // Transaction Capabilities
    X12_SEGMENT_TXP = EDI_HASH('T', 'X', 'P'),  // Tax Payment
    X12_SEGMENT_UC  = EDI_HASH('U', 'C', NIL),  // Underwriting Category
    X12_SEGMENT_UCS = EDI_HASH('U', 'C', 'S'),  // Underwriting Considerations
    X12_SEGMENT_UD  = EDI_HASH('U', 'D', NIL),  // Underwriting Status
    X12_SEGMENT_UDA = EDI_HASH('U', 'D', 'A'),  // Underwriting Condition
    X12_SEGMENT_UIT = EDI_HASH('U', 'I', 'T'),  // Unit Detail
    X12_SEGMENT_UM  = EDI_HASH('U', 'M', NIL),  // Health Care Services Review Information
    X12_SEGMENT_UPI = EDI_HASH('U', 'P', 'I'),  // Universal Product Identification
    X12_SEGMENT_UQS = EDI_HASH('U', 'Q', 'S'),  // Underwriting Question
    X12_SEGMENT_UR  = EDI_HASH('U', 'R', NIL),  // Peer Review Organization or Utilization Review
    X12_SEGMENT_USD = EDI_HASH('U', 'S', 'D'),  // Usage-Sensitive Detail
    X12_SEGMENT_USI = EDI_HASH('U', 'S', 'I'),  // Unitized Shipment Information
    X12_SEGMENT_UWI = EDI_HASH('U', 'W', 'I'),  // Underwriting Information
    X12_SEGMENT_V1  = EDI_HASH('V', '1', NIL),  // Vessel Identification
    X12_SEGMENT_V2  = EDI_HASH('V', '2', NIL),  // Vessel Information
    X12_SEGMENT_V3  = EDI_HASH('V', '3', NIL),  // Vessel Schedule
    X12_SEGMENT_V4  = EDI_HASH('V', '4', NIL),  // Cargo Location Reference
    X12_SEGMENT_V5  = EDI_HASH('V', '5', NIL),  // Vessel Identification
    X12_SEGMENT_V9  = EDI_HASH('V', '9', NIL),  // Event Detail
    X12_SEGMENT_VAD = EDI_HASH('V', 'A', 'D'),  // Vehicle Advice Detail
    X12_SEGMENT_VAR = EDI_HASH('V', 'A', 'R'),  // Credit File Variation
    X12_SEGMENT_VAT = EDI_HASH('V', 'A', 'T'),  // Vehicle Attribute
    X12_SEGMENT_VC  = EDI_HASH('V', 'C', NIL),  // Motor Vehicle Control
    X12_SEGMENT_VC1 = EDI_HASH('V', 'C', '1'),  // Vehicle Detail
    X12_SEGMENT_VDI = EDI_HASH('V', 'D', 'I'),  // Value Description or Information
    X12_SEGMENT_VEH = EDI_HASH('V', 'E', 'H'),  // Vehicle Information
    X12_SEGMENT_VID = EDI_HASH('V', 'I', 'D'),  // Conveyance Identification
    X12_SEGMENT_VR  = EDI_HASH('V', 'R', NIL),  // Rate Origin
    X12_SEGMENT_VRC = EDI_HASH('V', 'R', 'C'),  // Vehicle Recovery
    X12_SEGMENT_W01 = EDI_HASH('W', '0', '1'),  // Line Item Detail - Warehouse
    X12_SEGMENT_W03 = EDI_HASH('W', '0', '3'),  // Total Shipment Information (Warehouse)
    X12_SEGMENT_W04 = EDI_HASH('W', '0', '4'),  // Item Detail Total
    X12_SEGMENT_W05 = EDI_HASH('W', '0', '5'),  // Shipping Order Identification
    X12_SEGMENT_W06 = EDI_HASH('W', '0', '6'),  // Warehouse Shipment Identification
    X12_SEGMENT_W07 = EDI_HASH('W', '0', '7'),  // Item Detail For Stock Receipt
    X12_SEGMENT_W08 = EDI_HASH('W', '0', '8'),  // Receipt Carrier Information
    X12_SEGMENT_W09 = EDI_HASH('W', '0', '9'),  // Equipment and Temperature
    X12_SEGMENT_W1  = EDI_HASH('W', '1', NIL),  // Block Identification
    X12_SEGMENT_W10 = EDI_HASH('W', '1', '0'),  // Warehouse Additional Carrier Information
    X12_SEGMENT_W12 = EDI_HASH('W', '1', '2'),  // Warehouse Item Detail
    X12_SEGMENT_W13 = EDI_HASH('W', '1', '3'),  // Item Detail Exception
    X12_SEGMENT_W14 = EDI_HASH('W', '1', '4'),  // Total Receipt Information
    X12_SEGMENT_W15 = EDI_HASH('W', '1', '5'),  // Warehouse Adjustment Identification
    X12_SEGMENT_W17 = EDI_HASH('W', '1', '7'),  // Warehouse Receipt Identification
    X12_SEGMENT_W18 = EDI_HASH('W', '1', '8'),  // Probe Temperatures
    X12_SEGMENT_W19 = EDI_HASH('W', '1', '9'),  // Warehouse Adjustment Item Detail
    X12_SEGMENT_W2  = EDI_HASH('W', '2', NIL),  // Equipment Identification
    X12_SEGMENT_W20 = EDI_HASH('W', '2', '0'),  // Line Item Detail - Packing
    X12_SEGMENT_W27 = EDI_HASH('W', '2', '7'),  // Carrier Details (Warehouse)
    X12_SEGMENT_W28 = EDI_HASH('W', '2', '8'),  // Consolidation Information
    X12_SEGMENT_W3  = EDI_HASH('W', '3', NIL),  // Consignee Information
    X12_SEGMENT_W4  = EDI_HASH('W', '4', NIL),  // Consignor Information
    X12_SEGMENT_W5  = EDI_HASH('W', '5', NIL),  // Carrier and Route Information
    X12_SEGMENT_W6  = EDI_HASH('W', '6', NIL),  // Special Handling Information
    X12_SEGMENT_W66 = EDI_HASH('W', '6', '6'),  // Warehouse Carrier Information
    X12_SEGMENT_W76 = EDI_HASH('W', '7', '6'),  // Total Shipping Order
    X12_SEGMENT_WIN = EDI_HASH('W', 'I', 'N'),  // Wine Information
    X12_SEGMENT_WLD = EDI_HASH('W', 'L', 'D'),  // Workload Detail
    X12_SEGMENT_WS  = EDI_HASH('W', 'S', NIL),  // Work Schedule
    X12_SEGMENT_X01 = EDI_HASH('X', '0', '1'),  // Automated Manifest Archive Status Details
    X12_SEGMENT_X02 = EDI_HASH('X', '0', '2'),  // Automated Manifest Bills Eligible/Overdue Archive Details
    X12_SEGMENT_X1  = EDI_HASH('X', '1', NIL),  // Export License
    X12_SEGMENT_X2  = EDI_HASH('X', '2', NIL),  // Import License
    X12_SEGMENT_X4  = EDI_HASH('X', '4', NIL),  // Customs Release Information
    X12_SEGMENT_X7  = EDI_HASH('X', '7', NIL),  // Customs Information
    X12_SEGMENT_XD  = EDI_HASH('X', 'D', NIL),  // Placement/Pull Data
    X12_SEGMENT_XH  = EDI_HASH('X', 'H', NIL),  // Pro Forma - B13 Information
    X12_SEGMENT_XPO = EDI_HASH('X', 'P', 'O'),  // Preassigned Purchase Order Numbers
    X12_SEGMENT_XQ  = EDI_HASH('X', 'Q', NIL),  // Reporting Date/Action
    X12_SEGMENT_Y1  = EDI_HASH('Y', '1', NIL),  // Space Reservation Request
    X12_SEGMENT_Y2  = EDI_HASH('Y', '2', NIL),  // Container Details
    X12_SEGMENT_Y3  = EDI_HASH('Y', '3', NIL),  // Space Confirmation
    X12_SEGMENT_Y4  = EDI_HASH('Y', '4', NIL),  // Container Release
    X12_SEGMENT_Y5  = EDI_HASH('Y', '5', NIL),  // Space Booking Cancellation
    X12_SEGMENT_Y6  = EDI_HASH('Y', '6', NIL),  // Authentication
    X12_SEGMENT_Y7  = EDI_HASH('Y', '7', NIL),  // Cargo Booking Priority
    X12_SEGMENT_YNQ = EDI_HASH('Y', 'N', 'Q'),  // Yes/No Question
    X12_SEGMENT_ZA  = EDI_HASH('Z', 'A', NIL),  // Product Activity Reporting
    X12_SEGMENT_ZC1 = EDI_HASH('Z', 'C', '1'),  // Beginning Segment for Data Correction or Change
    X12_SEGMENT_ZD  = EDI_HASH('Z', 'D', NIL),  // Transaction Set Deletion - ID, Reason, and Source
    X12_SEGMENT_ZR  = EDI_HASH('Z', 'R', NIL),  // Waybill Reference Identification
    X12_SEGMENT_ZT  = EDI_HASH('Z', 'T', NIL),  // Waybill Request Information

} EDISegmentType;

#endif
